// AUTO-GENERATED from production `protocols`/`protocol_items` (kind=action, chronological).
// Hero GOALS -> named PROTOCOLS -> exact day-timeline items + the real protocol description.
import type { ProtocolItem } from "./protocolCategories";

export interface RealProtocol {
  key: string; name: string; chip: string;
  description: string;
  creator?: string; source?: string; evidence?: string;
  days?: number; score?: number;
  items: ProtocolItem[];
}
export interface Goal { key: string; label: string; pillar: "Health" | "Beauty" | "Fitness"; protocols: RealProtocol[]; }

export const GOALS: Goal[] = [
  {
    key: "health", label: "Health", pillar: "Health",
    protocols: [
      {
        key: "self-heal-women", name: "Self Heal by Design — Women", chip: "Women",
        description: "A women-tailored version of Barbara O'Neill's Self Heal by Design protocol, with hormone-cycle awareness baked into the rhythm. Same foundational routine — morning sun, intermittent fasting, raw plants, sleep hygiene — plus Wild Yam Cream (Female) for natural progesterone support, evening primrose, and a heavier emphasis on liver decongestion (castor-oil packs, dandelion bitters) that female sex hormones depend on. Why it matters: Barbara teaches that most modern female symptoms — heavy periods, PMS, hot flushes, mood — trace back to estrogen dominance from a congested liver and poor sleep, and this protocol is her clinical answer to that pattern. Source: Self Heal by Design (book) + Misty Mountain Health Retreat curriculum",
        score: 88, evidence: "moderate",
        items: [
          { name: "Gratitude on Waking", item_type: "activity", meta: "05:30" },
          { name: "Tongue Scraping", item_type: "activity", meta: "05:35" },
          { name: "Warm Lemon Water", item_type: "consume", meta: "05:40" },
          { name: "Apple Cider Vinegar Tonic", item_type: "supplement", meta: "05:50" },
          { name: "Oil Pulling", item_type: "activity", meta: "06:00" },
          { name: "Dry Skin Brushing", item_type: "activity", meta: "06:15" },
          { name: "Hot/Cold Contrast Shower", item_type: "activity", meta: "06:20" },
          { name: "Barefoot Grounding", item_type: "activity", meta: "06:30" },
          { name: "Morning Sunlight", item_type: "activity", meta: "06:35" },
          { name: "4-7-8 Breathing", item_type: "activity", meta: "06:55" },
          { name: "Rebounding", item_type: "activity", meta: "07:00" },
          { name: "Spinal Mobility", item_type: "activity", meta: "07:15" },
          { name: "Beetroot", item_type: "consume", meta: "07:30" },
          { name: "Freshly Ground Flaxseed", item_type: "supplement", meta: "07:45" },
          { name: "Soaked Oats with Berries, Flax & Raw Honey", item_type: "consume", meta: "08:00" },
          { name: "Brisk Walk After Breakfast", item_type: "activity", meta: "08:35" },
          { name: "Meditation", item_type: "activity", meta: "09:00" },
          { name: "Big Rainbow Salad with Sprouts", item_type: "consume", meta: "12:30" },
          { name: "Brisk Walk After Lunch", item_type: "activity", meta: "13:15" },
          { name: "Midday Sun for Vitamin D", item_type: "activity", meta: "14:00" },
          { name: "Daily Nature Time", item_type: "activity", meta: "15:00" },
          { name: "Infrared / Steam Sauna", item_type: "activity", meta: "16:00" },
        ],
      },
      {
        key: "self-heal-men", name: "Self Heal by Design — Men", chip: "Men",
        description: "A male-tailored version of Barbara O'Neill's Self Heal by Design protocol. Same foundational routine — morning sun, intermittent fasting, raw plants, hydration, sleep hygiene — plus Wild Yam Cream (Male), prostate-supportive saw palmetto and pumpkin seed protein, heavier morning movement (Pilates or brisk walking), and cold-water hydrotherapy for testosterone signalling. Why it matters: Barbara argues that adult male symptoms — declining energy, libido, brain fog, abdominal fat — track back to insulin resistance, sleep debt, and an inflamed liver, and the male variant of the protocol is her practical playbook for reversing that arc. Source: Self Heal by Design (book) + Mountain Skies Wellness Retreat. Wild Yam Cream",
        score: 88, evidence: "moderate",
        items: [
          { name: "Gratitude on Waking", item_type: "activity", meta: "05:30" },
          { name: "Tongue Scraping", item_type: "activity", meta: "05:35" },
          { name: "Warm Lemon Water", item_type: "consume", meta: "05:40" },
          { name: "Apple Cider Vinegar Tonic", item_type: "supplement", meta: "05:50" },
          { name: "Oil Pulling", item_type: "activity", meta: "06:00" },
          { name: "Dry Skin Brushing", item_type: "activity", meta: "06:15" },
          { name: "Hot/Cold Contrast Shower", item_type: "activity", meta: "06:20" },
          { name: "Barefoot Grounding", item_type: "activity", meta: "06:30" },
          { name: "Morning Sunlight", item_type: "activity", meta: "06:35" },
          { name: "4-7-8 Breathing", item_type: "activity", meta: "06:55" },
          { name: "Rebounding", item_type: "activity", meta: "07:00" },
          { name: "Spinal Mobility", item_type: "activity", meta: "07:15" },
          { name: "Beetroot", item_type: "consume", meta: "07:30" },
          { name: "Freshly Ground Flaxseed", item_type: "supplement", meta: "07:45" },
          { name: "Soaked Oats with Berries, Flax & Raw Honey", item_type: "consume", meta: "08:00" },
          { name: "Brisk Walk After Breakfast", item_type: "activity", meta: "08:35" },
          { name: "Meditation", item_type: "activity", meta: "09:00" },
          { name: "Big Rainbow Salad with Sprouts", item_type: "consume", meta: "12:30" },
          { name: "Brisk Walk After Lunch", item_type: "activity", meta: "13:15" },
          { name: "Midday Sun for Vitamin D", item_type: "activity", meta: "14:00" },
          { name: "Daily Nature Time", item_type: "activity", meta: "15:00" },
          { name: "Infrared / Steam Sauna", item_type: "activity", meta: "16:00" },
        ],
      },
      {
        key: "self-heal-teen-female", name: "Self Heal by Design — Teen Female", chip: "Teen Female",
        description: "A gentler version of Barbara O'Neill's Self Heal by Design protocol tailored for teen girls (13–19). Same plant-based, sun-based, sleep-based principles, with quantities and intensity scaled down for adolescent physiology: no extended fasting, fruit-rich breakfast, no caffeine, screen curfew 90 minutes before bed. Adds menstrual-cycle awareness — castor-oil packs in the luteal phase, magnesium glycinate at night for cramps, iron-supportive foods (parsley, beetroot, dark leafy greens, soaked pumpkin seeds) around menstruation — plus Wild Yam Cream (Teen) for the hormonal transition years. Why it matters: Barbara teaches that the teenage decade is when lifelong hormone, gut, mood, and circadian patterns are set — and that early support during the menarche years (12–16) prevents the heavy periods, PMS, acne, and mood swings most women carry into adulthood. Source: Self Heal by Design (book), chapters on growth, puberty and the menstrual cycle",
        score: 86, evidence: "moderate",
        items: [
          { name: "Gratitude on Waking", item_type: "activity", meta: "05:30" },
          { name: "Tongue Scraping", item_type: "activity", meta: "05:35" },
          { name: "Warm Lemon Water", item_type: "consume", meta: "05:40" },
          { name: "Apple Cider Vinegar Tonic", item_type: "supplement", meta: "05:50" },
          { name: "Oil Pulling", item_type: "activity", meta: "06:00" },
          { name: "Dry Skin Brushing", item_type: "activity", meta: "06:15" },
          { name: "Hot/Cold Contrast Shower", item_type: "activity", meta: "06:20" },
          { name: "Barefoot Grounding", item_type: "activity", meta: "06:30" },
          { name: "Morning Sunlight", item_type: "activity", meta: "06:35" },
          { name: "4-7-8 Breathing", item_type: "activity", meta: "06:55" },
          { name: "Rebounding", item_type: "activity", meta: "07:00" },
          { name: "Spinal Mobility", item_type: "activity", meta: "07:15" },
          { name: "Beetroot", item_type: "consume", meta: "07:30" },
          { name: "Freshly Ground Flaxseed", item_type: "supplement", meta: "07:45" },
          { name: "Soaked Oats with Berries, Flax & Raw Honey", item_type: "consume", meta: "08:00" },
          { name: "Brisk Walk After Breakfast", item_type: "activity", meta: "08:35" },
          { name: "Meditation", item_type: "activity", meta: "09:00" },
          { name: "Big Rainbow Salad with Sprouts", item_type: "consume", meta: "12:30" },
          { name: "Brisk Walk After Lunch", item_type: "activity", meta: "13:15" },
          { name: "Midday Sun for Vitamin D", item_type: "activity", meta: "14:00" },
          { name: "Daily Nature Time", item_type: "activity", meta: "15:00" },
          { name: "Infrared / Steam Sauna", item_type: "activity", meta: "16:00" },
        ],
      },
      {
        key: "self-heal-teen-male", name: "Self Heal by Design — Teen Male", chip: "Teen Male",
        description: "A gentler version of Barbara O'Neill's Self Heal by Design protocol tailored for teen boys (13–19). Same plant-based, sun-based, sleep-based principles, with quantities and intensity scaled down for adolescent physiology: no extended fasting, fruit-rich breakfast, no caffeine, screen curfew 90 minutes before bed. Adds growth-window emphasis — heavier whole-protein intake (eggs, fish, lentils, pumpkin-seed protein), morning resistance training to drive growth-hormone and testosterone signalling, zinc-rich foods for skin and reproductive maturation, cold-water exposure for vagal tone, and 8.5+ hours of sleep (essential during the puberty growth surge). Why it matters: Barbara teaches that adolescent boys lay down lifelong bone density, mitochondrial capacity, gut integrity and circadian patterns during this decade — early adoption of the rhythm prevents the metabolic, mood and energy decline most men encounter in their thirties. Source: Self Heal by Design (book), chapters on growth, puberty and male development",
        score: 86, evidence: "moderate",
        items: [
          { name: "Gratitude on Waking", item_type: "activity", meta: "05:30" },
          { name: "Tongue Scraping", item_type: "activity", meta: "05:35" },
          { name: "Warm Lemon Water", item_type: "consume", meta: "05:40" },
          { name: "Apple Cider Vinegar Tonic", item_type: "supplement", meta: "05:50" },
          { name: "Oil Pulling", item_type: "activity", meta: "06:00" },
          { name: "Dry Skin Brushing", item_type: "activity", meta: "06:15" },
          { name: "Hot/Cold Contrast Shower", item_type: "activity", meta: "06:20" },
          { name: "Barefoot Grounding", item_type: "activity", meta: "06:30" },
          { name: "Morning Sunlight", item_type: "activity", meta: "06:35" },
          { name: "4-7-8 Breathing", item_type: "activity", meta: "06:55" },
          { name: "Rebounding", item_type: "activity", meta: "07:00" },
          { name: "Spinal Mobility", item_type: "activity", meta: "07:15" },
          { name: "Beetroot", item_type: "consume", meta: "07:30" },
          { name: "Freshly Ground Flaxseed", item_type: "supplement", meta: "07:45" },
          { name: "Soaked Oats with Berries, Flax & Raw Honey", item_type: "consume", meta: "08:00" },
          { name: "Brisk Walk After Breakfast", item_type: "activity", meta: "08:35" },
          { name: "Meditation", item_type: "activity", meta: "09:00" },
          { name: "Big Rainbow Salad with Sprouts", item_type: "consume", meta: "12:30" },
          { name: "Brisk Walk After Lunch", item_type: "activity", meta: "13:15" },
          { name: "Midday Sun for Vitamin D", item_type: "activity", meta: "14:00" },
          { name: "Daily Nature Time", item_type: "activity", meta: "15:00" },
          { name: "Infrared / Steam Sauna", item_type: "activity", meta: "16:00" },
        ],
      },
    ],
  },
  {
    key: "weight-loss", label: "Weight loss", pillar: "Health",
    protocols: [
      {
        key: "weight-loss-caloric-deficit", name: "Weight Loss — Caloric Deficit", chip: "Caloric Deficit",
        description: "A structured daily protocol combining intermittent fasting, HIIT training, strength work, and nutrient-dense meals to support sustainable fat loss while preserving lean muscle.\n\n**What it does to the body:**\n• Creates a 300-500 calorie daily deficit — the evidence-based sweet spot for fat loss without metabolic slowdown.\n• Morning fasted cardio (Zone 2) depletes liver glycogen overnight, forcing the body to oxidise stored fat as primary fuel.\n• HIIT sessions spike EPOC (excess post-exercise oxygen consumption), burning an additional 80-150 calories for 12-24 hours post-workout.\n• High-protein meals (40g+ per sitting) stimulate muscle protein synthesis via mTOR pathway, preventing lean mass loss during deficit.\n• Apple cider vinegar (1 tbsp) improves insulin sensitivity by 19-34% during high-carb meals (Johnston et al., 2004).\n• Post-dinner walking reduces postprandial glucose spikes by 30% (DiPietro et al., 2013).\n\n**Who created it:** Evidence-based protocol compiled from metabolic research by Dr. Layne Norton, Dr. Eric Helms, and ISSN position stands on fat loss.\n\n**Who it's for:** Adults 16+ with BMI >25 or those seeking body recomposition. Not suitable during pregnancy or for individuals with eating disorders.",
        creator: "Evidence-based weight loss protocol", source: "Evidence-based weight loss protocol", evidence: "moderate", score: 88,
        items: [
          { name: "Lemon Water", item_type: "consume", meta: "06:30" },
          { name: "Moderate Cardio", item_type: "activity", meta: "07:00" },
          { name: "High-Protein Breakfast", item_type: "consume", meta: "10:00" },
          { name: "Hiit All-Out", item_type: "activity", meta: "12:00" },
          { name: "Post-Workout Shake", item_type: "consume", meta: "13:00" },
          { name: "Balanced Lunch", item_type: "consume", meta: "14:00" },
          { name: "Light Dinner", item_type: "consume", meta: "18:00" },
          { name: "Evening Walk", item_type: "activity", meta: "19:30" },
        ],
      },
      {
        key: "master-cleanse-lemonade-diet", name: "Master Cleanse (lemonade Diet)", chip: "Master Cleanse",
        description: "Stanley Burroughs' original Master Cleanse from 1976 — a liquid fast using fresh lemon juice, grade B maple syrup, and cayenne pepper as the sole nutrition source for 10 days. The salt water flush each morning mechanically clears the entire digestive tract. Includes 3-day ease-in and 3-day ease-out phases.",
        creator: "Stanley Burroughs", evidence: "traditional", days: 16, score: 61,
        items: [
          { name: "Salt Water Flush", item_type: "consume", meta: "06:30" },
          { name: "Herbal Laxative Tea", item_type: "consume", meta: "21:00" },
          { name: "Ease-Out Day 3: Light whole foods", item_type: "consume" },
          { name: "Ease-In Day 1: Eliminate processed food, eat only whole foods", item_type: "consume" },
          { name: "Ease-In Day 3: Fresh orange juice all day", item_type: "consume" },
          { name: "Ease-Out Day 1: Fresh orange juice only", item_type: "consume" },
          { name: "Ease-In Day 2: Liquids and soups only", item_type: "consume" },
          { name: "Ease-Out Day 2: Soups and juices", item_type: "consume" },
          { name: "Walking", item_type: "activity" },
          { name: "Master Cleanse Lemonade", item_type: "consume" },
          { name: "Drink Water", item_type: "activity" },
        ],
      },
    ],
  },
  {
    key: "clearer-skin", label: "Clearer skin", pillar: "Beauty",
    protocols: [
      {
        key: "korean-glass-skin-ritual", name: "Korean Glass Skin Ritual", chip: "Glass Skin",
        description: "The signature **glass skin** (유리 피부) ritual — the poreless, dewy, lit-from-within look associated with Korean celebrities. It's all about hydration layering.\n\n### The ritual\nDouble cleanse → gentle exfoliate → the 7-skin method (layer toner 3–7×) → snail-mucin essence → hyaluronic serum → moisturizer → a setting mist, finished at night with a sleeping mask.\n\n### Why it works\n**Glass skin is hydration, not coverage.** Patting many thin watery layers into damp skin plumps it from within so light bounces off an even, dewy surface.\n\nEducational beauty content reflecting popular Korean skincare practice — not medical advice.",
        source: "Korean skincare (K-beauty) practice", evidence: "moderate", score: 81,
        items: [
          { name: "Oil Cleanse", item_type: "activity", meta: "07:00" },
          { name: "Water Cleanse", item_type: "activity", meta: "07:03" },
          { name: "Gentle Exfoliant", item_type: "activity", meta: "07:06" },
          { name: "7-Skin Method", item_type: "activity", meta: "07:09" },
          { name: "Snail Mucin Essence", item_type: "activity", meta: "07:14" },
          { name: "Hyaluronic Serum", item_type: "activity", meta: "07:17" },
          { name: "Moisturizer", item_type: "activity", meta: "07:20" },
          { name: "Setting Mist", item_type: "activity", meta: "07:23" },
          { name: "Gua Sha Massage", item_type: "activity", meta: "07:26" },
          { name: "Sleeping Mask", item_type: "activity", meta: "21:30" },
        ],
      },
      {
        key: "k-beauty-morning-routine", name: "K-Beauty Morning Routine", chip: "K-Beauty AM",
        description: "The Korean morning skincare routine — a light, hydration-first sequence that preps and protects skin for the day.\n\n### The order\nGentle cleanse, hydrating toner, essence, a brightening Vitamin C serum, eye cream, moisturizer, and — non-negotiable — SPF 50+.\n\n### Why it works\n**Mornings are about protection, not heavy treatment.** Light layers of hydration sit under sunscreen so skin stays dewy and defended all day. Pat each layer in; never rub.\n\nEducational beauty content reflecting popular Korean skincare practice — not medical advice.",
        source: "Korean skincare (K-beauty) practice", evidence: "moderate", score: 76,
        items: [
          { name: "Gentle Morning Cleanse", item_type: "activity", meta: "06:30" },
          { name: "Hydrating Toner", item_type: "activity", meta: "06:33" },
          { name: "Essence", item_type: "activity", meta: "06:36" },
          { name: "Vitamin C Serum", item_type: "activity", meta: "06:39" },
          { name: "Eye Cream", item_type: "activity", meta: "06:42" },
          { name: "Moisturizer", item_type: "activity", meta: "06:45" },
          { name: "Sunscreen SPF 50+", item_type: "activity", meta: "06:48" },
        ],
      },
      {
        key: "hailey-bieber-glazed-skin-routine", name: "Hailey Bieber Glazed Skin Routine", chip: "Hailey Bieber",
        description: "The viral glazed donut skin protocol built on deep hydration, peptides, and barrier repair. Morning: gentle cleanser, niacinamide toner, hyaluronic acid serum, peptide moisturiser, SPF 50. Evening: double cleanse, retinol 0.5%, barrier cream, facial gua sha massage. The goal is lit-from-within luminosity, not heavy coverage.",
        creator: "Hailey Bieber", evidence: "moderate", score: 77,
        items: [
          { name: "Micellar Water Cleanse", item_type: "activity", meta: "06:30" },
          { name: "Vitamin C Brightening Serum", item_type: "supplement", meta: "06:33" },
          { name: "Hyaluronic Acid Hydrating Serum", item_type: "activity", meta: "06:35" },
          { name: "Peptide-Rich Moisturizer", item_type: "activity", meta: "06:37" },
          { name: "Sunscreen Application", item_type: "activity", meta: "06:39" },
          { name: "Lip Gloss", item_type: "activity", meta: "06:41" },
          { name: "Collagen Peptides", item_type: "supplement", meta: "07:30" },
          { name: "Biotin", item_type: "supplement", meta: "07:32" },
          { name: "Vitamin C", item_type: "supplement", meta: "07:33" },
          { name: "Hyaluronic Acid Capsule", item_type: "supplement", meta: "07:34" },
          { name: "Zinc", item_type: "supplement", meta: "07:35" },
          { name: "Beauty Water", item_type: "consume", meta: "08:00" },
          { name: "Lunch", item_type: "consume", meta: "12:30" },
          { name: "Face Mist Refresh", item_type: "activity", meta: "12:30" },
          { name: "Spf Touch-Up Reapplication", item_type: "activity", meta: "13:00" },
          { name: "Gua Sha Face Massage", item_type: "activity", meta: "13:05" },
          { name: "Oil Cleanser First Pass", item_type: "activity", meta: "20:30" },
          { name: "Foaming Cleanser", item_type: "activity", meta: "20:33" },
          { name: "Retinol Serum 0.3% Application", item_type: "activity", meta: "20:35" },
          { name: "Niacinamide", item_type: "activity", meta: "20:37" },
          { name: "Sleeping", item_type: "activity", meta: "20:39" },
          { name: "Eye Cream", item_type: "activity", meta: "20:41" },
        ],
      },
    ],
  },
  {
    key: "lean-muscle", label: "Lean muscle", pillar: "Fitness",
    protocols: [
      {
        key: "muscle-gain-caloric-surplus", name: "Muscle Gain — Caloric Surplus", chip: "Caloric Surplus",
        description: "A structured daily protocol with progressive overload training, caloric surplus meals, and recovery optimization to build lean muscle mass effectively.\n\n**What it does to the body:**\n• 300-500 calorie surplus provides the energy substrate required for muscle protein synthesis without excessive fat gain.\n• Progressive overload strength training (4-6 rep range) recruits Type II fast-twitch muscle fibres, maximising mechanical tension — the primary driver of hypertrophy.\n• 1.6-2.2g protein per kg bodyweight saturates muscle protein synthesis, with 50g post-workout triggering maximal mTOR activation.\n• Creatine monohydrate (5g daily) increases phosphocreatine stores by 20-40%, improving strength output and cell volumisation.\n• Casein protein before bed provides sustained amino acid release over 6-8 hours, reducing overnight muscle protein breakdown by 34% (Res et al., 2012).\n• Push/Pull/Legs split allows 48-72 hours recovery per muscle group — optimal for satellite cell repair and supercompensation.\n\n**Who created it:** Based on research by Dr. Brad Schoenfeld (hypertrophy science), Dr. Eric Helms (The Muscle & Strength Pyramid), and NSCA guidelines.\n\n**Who it's for:** Adults 16+ looking to gain lean muscle mass. Requires access to a gym with free weights and machines.",
        creator: "Evidence-based hypertrophy protocol", source: "Evidence-based hypertrophy protocol", evidence: "moderate", score: 85,
        items: [
          { name: "Pre-Breakfast Shake", item_type: "consume", meta: "06:30" },
          { name: "High-Calorie Breakfast", item_type: "consume", meta: "07:30" },
          { name: "Mid-Morning Snack", item_type: "consume", meta: "10:00" },
          { name: "Strength Training", item_type: "activity", meta: "11:00" },
          { name: "Post-Workout Meal", item_type: "consume", meta: "12:30" },
          { name: "Lunch", item_type: "consume", meta: "15:00" },
          { name: "Dinner", item_type: "consume", meta: "19:00" },
          { name: "Before Bed Casein Shake", item_type: "consume", meta: "21:30" },
        ],
      },
      {
        key: "the-rock-iron-paradise-workout", name: "The Rock Iron Paradise Workout", chip: "The Rock",
        description: "Iron Paradise 6-day split: 30-60 min fasted cardio every morning, then heavy weight training. Rotating push/pull/legs with high volume. Sunday is cheat meal and active recovery day.",
        creator: "Dwayne Johnson", evidence: "high", score: 86,
        items: [
          { name: "Pre-Workout Stimulant", item_type: "supplement", meta: "03:30" },
          { name: "Wake 4am", item_type: "activity", meta: "04:00" },
          { name: "Pre-Cardio", item_type: "consume", meta: "04:03" },
          { name: "Incline Treadmill", item_type: "activity", meta: "04:10" },
          { name: "Intra-Workout Bcaas", item_type: "supplement", meta: "05:00" },
          { name: "Breakfast", item_type: "consume", meta: "05:00" },
          { name: "Post-Workout Whey Isolate", item_type: "supplement", meta: "07:00" },
          { name: "Creatine Hcl", item_type: "supplement", meta: "07:05" },
          { name: "Second Meal", item_type: "consume", meta: "08:00" },
          { name: "Barbell Back Squat", item_type: "activity", meta: "09:30" },
          { name: "Leg Press", item_type: "activity", meta: "09:50" },
          { name: "Leg Extension", item_type: "activity", meta: "10:05" },
          { name: "Romanian Deadlift", item_type: "activity", meta: "10:15" },
          { name: "Walking Lunges", item_type: "activity", meta: "10:27" },
          { name: "Standing Calf Raises", item_type: "activity", meta: "10:39" },
          { name: "Core Circuit", item_type: "activity", meta: "10:50" },
          { name: "Post-Workout Shake", item_type: "consume", meta: "11:10" },
          { name: "Sunday Cheat Meal", item_type: "consume", meta: "12:00" },
        ],
      },
      {
        key: "functional-training-circuit", name: "Functional Training Circuit", chip: "Functional",
        description: "A full-body functional circuit built on the five fundamental movement patterns — squat, hinge, push, pull, and carry. Trains strength that transfers to everyday movement; scalable from bodyweight to loaded.",
        creator: "HealthScan", evidence: "moderate", days: 1,
        items: [
          { name: "Dynamic Warm-Up", item_type: "activity", meta: "07:00" },
          { name: "Goblet Squat", item_type: "activity", meta: "07:03" },
          { name: "Romanian Deadlift", item_type: "activity", meta: "07:06" },
          { name: "Push-Ups", item_type: "activity", meta: "07:09" },
          { name: "Bent-Over Row", item_type: "activity", meta: "07:12" },
          { name: "Farmer's Carry", item_type: "activity", meta: "07:15" },
          { name: "Functional Circuit Round", item_type: "activity", meta: "07:16" },
        ],
      },
    ],
  },
  {
    key: "more-energy", label: "More energy", pillar: "Health",
    protocols: [
      {
        key: "optimal-morning-routine", name: "Optimal Morning Routine", chip: "Optimal Morning",
        description: "A science-backed morning protocol combining light exposure, cold therapy, mindfulness, movement, and nutrition to maximize energy, focus, and hormonal balance for the day ahead.\n\n**Morning Flow:**\n• 6:00 AM - Wake up with natural light exposure\n• 6:15 AM - Cold shower or cold plunge (2-3 min)\n• 6:30 AM - 10 min meditation/breathwork\n• 6:45 AM - Light movement/stretching (15 min)\n• 7:00 AM - Hydration + electrolytes\n• 7:15 AM - Nutrient-dense breakfast\n• 7:45 AM - Morning sunlight walk (20 min)\n• 8:15 AM - Caffeine (if desired) + deep work block\n\n**Benefits:**\n- Regulates circadian rhythm\n- Boosts dopamine and alertness\n- Supports metabolic health\n- Enhances cognitive performance",
        creator: "Optimal Morning Protocol", source: "Optimal Morning Protocol", evidence: "moderate", days: 1, score: 92,
        items: [
          { name: "Light Exposure", item_type: "activity", meta: "06:00" },
          { name: "Cold Shower/plunge", item_type: "activity", meta: "06:15" },
          { name: "Meditation", item_type: "activity", meta: "06:30" },
          { name: "Morning Movement", item_type: "activity", meta: "06:45" },
          { name: "Morning Hydration", item_type: "consume", meta: "07:00" },
          { name: "Creatine Monohydrate", item_type: "supplement", meta: "07:15" },
          { name: "Vitamin D3", item_type: "supplement", meta: "07:15" },
          { name: "Omega-3", item_type: "supplement", meta: "07:15" },
          { name: "Nutrient-Dense Breakfast", item_type: "consume", meta: "07:15" },
          { name: "Morning Sunlight Walk", item_type: "activity", meta: "07:45" },
          { name: "Deep Work / Focus Time", item_type: "activity", meta: "08:15" },
          { name: "Caffeine", item_type: "supplement", meta: "08:15" },
        ],
      },
      {
        key: "wim-hof-breathing-cold-method", name: "Wim Hof Breathing & Cold Method", chip: "Wim Hof",
        description: "The Iceman's clinically-proven protocol: 3 rounds of 30-40 power breaths (hyperventilation) followed by breath retention after exhale, then recovery breath hold. Followed by cold shower or ice bath. Proven in peer-reviewed studies to consciously influence immune response, reduce inflammation, and flood the body with energy. Start with 30 sec cold, build to 5+ minutes.",
        creator: "Wim Hof", evidence: "high", score: 89,
        items: [
          { name: "Pre-Breathing Hydration", item_type: "consume", meta: "05:50" },
          { name: "30 Power Breaths", item_type: "activity", meta: "06:00" },
          { name: "Recovery Breath", item_type: "activity", meta: "06:05" },
          { name: "Recovery Breath & Rest", item_type: "activity", meta: "06:22" },
          { name: "Cold Shower", item_type: "activity", meta: "06:30" },
          { name: "Ice Bath Full Immersion", item_type: "activity", meta: "06:40" },
          { name: "Wim Hof Controlled Breathing During Cold", item_type: "activity", meta: "06:42" },
          { name: "Post-Cold Warm-Up & Body Scan", item_type: "activity", meta: "06:45" },
          { name: "Meditation", item_type: "activity", meta: "07:00" },
          { name: "Commitment Affirmation & Mental Visualization", item_type: "activity", meta: "07:10" },
          { name: "Vitamin D3", item_type: "supplement", meta: "07:30" },
          { name: "Adaptogens", item_type: "supplement", meta: "07:31" },
          { name: "Electrolytes", item_type: "supplement", meta: "07:32" },
          { name: "Post-cold Meal", item_type: "consume", meta: "07:45" },
          { name: "Shower", item_type: "activity", meta: "17:00" },
          { name: "Breath Retention Progress Log", item_type: "activity", meta: "21:00" },
          { name: "Sleep", item_type: "activity", meta: "21:30" },
        ],
      },
      {
        key: "5am-club", name: "5am Club", chip: "5am Club",
        description: "Wake at 5am: 20 min vigorous exercise (Victory Hour), 20 min reflection and journaling, 20 min learning. The 20/20/20 formula used by world-class performers.",
        creator: "Robin Sharma", evidence: "high", score: 86,
        items: [
          { name: "Hot Lemon Water", item_type: "consume", meta: "05:00" },
          { name: "Green Tea Extract", item_type: "supplement", meta: "05:00" },
          { name: "Wake at 5am Sharp", item_type: "activity", meta: "05:00" },
          { name: "Hydration", item_type: "consume", meta: "05:00" },
          { name: "Vitamin B-Complex", item_type: "supplement", meta: "05:01" },
          { name: "Lion's Mane Mushroom", item_type: "supplement", meta: "05:02" },
          { name: "Vigorous Exercise", item_type: "activity", meta: "05:02" },
          { name: "Magnesium Glycinate", item_type: "supplement", meta: "05:03" },
          { name: "Focused Meditation", item_type: "activity", meta: "05:22" },
          { name: "Gratitude Journaling", item_type: "activity", meta: "05:32" },
          { name: "Read 10 Pages of World-Class Non-Fiction", item_type: "activity", meta: "05:42" },
          { name: "Educational Podcast or Masterclass Audio", item_type: "activity", meta: "05:54" },
          { name: "Nutritious Breakfast", item_type: "consume", meta: "06:05" },
          { name: "Morning Mindset Meal", item_type: "consume", meta: "07:00" },
          { name: "Vision Journaling", item_type: "activity" },
        ],
      },
    ],
  },
  {
    key: "better-sleep", label: "Better sleep", pillar: "Health",
    protocols: [
      {
        key: "matthew-walker-sleep-protocol", name: "Matthew Walker Sleep Protocol", chip: "Matthew Walker",
        description: "Cool bedroom to 18-19 C (65-67 F), complete blackout curtains, no alcohol (disrupts REM), consistent bed and wake times 7 days/week, no screens 1 hr before bed. Based on peer-reviewed sleep science.",
        creator: "Matthew Walker", evidence: "high", score: 96,
        items: [
          { name: "Avoid naps after 3pm", item_type: "activity", meta: "00:00" },
          { name: "No alcohol", item_type: "activity", meta: "00:00" },
          { name: "Wake at SAMe Time Every Day", item_type: "activity", meta: "06:00" },
          { name: "Last caffeine no later than 2pm", item_type: "activity", meta: "14:00" },
          { name: "Chamomile or Tart Cherry Juice", item_type: "consume", meta: "20:30" },
          { name: "Light Pre-sleep Snack", item_type: "consume", meta: "20:45" },
          { name: "Magnesium Glycinate", item_type: "supplement", meta: "21:00" },
          { name: "Stop all screens 1 hour before bed", item_type: "activity", meta: "21:00" },
          { name: "Glycine", item_type: "supplement", meta: "21:01" },
          { name: "Apigenin", item_type: "supplement", meta: "21:02" },
          { name: "Low-Dose Melatonin", item_type: "supplement", meta: "21:03" },
          { name: "Theanine", item_type: "supplement", meta: "21:04" },
          { name: "Light Reading Under Warm 40w Lamp or Candle", item_type: "activity", meta: "21:05" },
          { name: "Set Bedroom Thermostat to 18-19 C", item_type: "activity", meta: "21:50" },
          { name: "Sleep", item_type: "activity", meta: "21:52" },
          { name: "Progressive Muscle Relaxation", item_type: "activity", meta: "21:54" },
        ],
      },
      {
        key: "evening-wind-down", name: "Evening Wind-Down", chip: "Wind-Down",
        description: "A structured 90-minute pre-sleep protocol that lowers cortisol, supports deep sleep stages and reduces stress before bed. The most impactful thing you can do for next-day performance.\n\n**Sequence (8:00–9:30 PM):**\n• 8:00 PM – Magnesium Glycinate 400 mg + Ashwagandha 300 mg\n• 8:30 PM – Switch to blue-light-blocking glasses or warm lighting\n• 9:00 PM – Gentle yoga / yin stretch (10 min)\n• 9:30 PM – Evening journaling (gratitude + tomorrow's top 3 priorities)\n\n**The science:**\n- Magnesium activates GABA receptors — the brain's primary inhibitory neurotransmitter\n- Ashwagandha reduces cortisol by ~15–30% and improves sleep quality in double-blind trials\n- Blue light at night suppresses melatonin by up to 50% — amber glasses restore melatonin timing\n- 3–5 gratitude items before sleep reduce anxiety and improve morning mood",
        creator: "Evening Wind-Down Protocol", source: "Evening Wind-Down Protocol", evidence: "moderate", days: 1, score: 86,
        items: [
          { name: "Ashwagandha", item_type: "supplement", meta: "20:00" },
          { name: "Magnesium Glycinate", item_type: "supplement", meta: "20:00" },
          { name: "Blue Light Blocking", item_type: "activity", meta: "20:30" },
          { name: "Gentle Evening Stretch", item_type: "activity", meta: "21:00" },
          { name: "Evening Journaling", item_type: "activity", meta: "21:30" },
        ],
      },
    ],
  },
  {
    key: "gut-health", label: "Gut health", pillar: "Health",
    protocols: [
      {
        key: "gut-healing", name: "Gut Healing", chip: "Gut Healing",
        description: "Barbara O'Neill's 4-to-8-week protocol to heal and seal the gut lining — her standard answer to leaky gut, IBS, food sensitivities, autoimmunity, and chronic skin conditions. Builds on the 4-R framework: Remove (sugar, gluten, dairy, seed oils, alcohol, NSAIDs), Replace (digestive bitters, betaine HCl, digestive enzymes), Reinoculate (kefir, sauerkraut, kimchi, fibre-rich plants), Repair (bone broth, slippery elm, marshmallow root, aloe vera juice, L-glutamine, zinc carnosine, vitamin D). Adds intermittent fasting to give the gut digestive rest, stress regulation (the vagus nerve runs gut motility), and circadian-aligned eating. Why it matters: Barbara teaches the gut wall is the single most important barrier in the body — once it leaks, every downstream system (immune, hormonal, cognitive, skin) follows it into dysfunction. Source: Self Heal by Design (book) + \"Sustain Me\" (sequel), chapter on the gut-mucosal barrier.",
        creator: "Barbara O'Neill", source: "Barbara O'Neill — Self Heal by Design", evidence: "moderate", score: 85,
        items: [
          { name: "Bone broth", item_type: "consume", meta: "08:00" },
          { name: "Slippery elm before meals", item_type: "supplement", meta: "11:30" },
          { name: "Fermented Foods", item_type: "consume", meta: "12:30" },
          { name: "Aloe vera juice", item_type: "consume", meta: "16:00" },
          { name: "L-glutamine", item_type: "supplement", meta: "20:00" },
        ],
      },
      {
        key: "candida-cleanse-protocol", name: "Candida Cleanse Protocol", chip: "Candida Cleanse",
        description: "A targeted anti-candida protocol combining potent natural antifungals with biofilm disruptors and probiotics over 8 weeks. Candida overgrowth hides behind protective biofilm — this protocol breaks through that shield with enzymes like nattokinase and serrapeptase, then attacks exposed fungal colonies with caprylic acid, oregano oil, and pau d'arco. Strict sugar-free diet is non-negotiable. Phase 1 disrupts biofilm, Phase 2 kills candida, Phase 3 rebuilds gut flora.",
        creator: "Functional Medicine", evidence: "moderate", days: 56, score: 71,
        items: [
          { name: "Serrapeptase", item_type: "supplement", meta: "06:30" },
          { name: "NAC / N-Acetyl Cysteine", item_type: "supplement", meta: "06:30" },
          { name: "Nattokinase", item_type: "supplement", meta: "06:30" },
          { name: "Oregano Oil", item_type: "supplement", meta: "07:30" },
          { name: "Caprylic Acid", item_type: "supplement", meta: "07:30" },
          { name: "Pau D'arco", item_type: "supplement", meta: "13:00" },
          { name: "Saccharomyces Boulardii", item_type: "supplement", meta: "19:00" },
          { name: "Probiotic", item_type: "supplement", meta: "19:00" },
          { name: "Anti-candida foods: raw garlic, coconut oil, ginger, apple cider vinegar", item_type: "consume" },
          { name: "STRICT no sugar, no refined carbs, no alcohol, no fruit", item_type: "consume" },
          { name: "Expect", item_type: "activity" },
        ],
      },
    ],
  },
  {
    key: "healthy-kids", label: "Healthy kids", pillar: "Health",
    protocols: [
      {
        key: "child-nutrition-2-to-3-years", name: "Child Nutrition — 2 to 3 Years", chip: "Ages 2–3",
        description: "Supporting independent eating, varied food exposure, and physical development. Focus on preventing picky eating and ensuring adequate calcium, iron, and fiber intake.\n\n**What it does to the body:**\n• Fiber intake (19g/day target) establishes healthy gut microbiome diversity — children with diverse microbiomes by age 3 have 40% lower allergy and autoimmune disease rates.\n• Calcium (700mg/day) and phosphorus support the rapid long-bone growth occurring during the 2-3 year growth spurt (average 8-10cm/year).\n• Outdoor play for 45+ minutes provides UV-stimulated vitamin D synthesis and develops vestibular and proprioceptive systems critical for balance.\n• \"Hidden vegetable\" strategies (spinach in smoothies) increase micronutrient intake without triggering food rejection — research shows blended vegetables are accepted 3x more readily.\n• Creative and sensory play builds 1,000+ new neural connections per second at this age, supporting language, problem-solving, and emotional regulation.\n• Limiting added sugar to <25g/day prevents early childhood caries and reduces insulin resistance risk — taste preferences formed at this age persist into adulthood.\n\n**Who created it:** Based on AAP early childhood nutrition guidelines, CDC growth milestone benchmarks, and pediatric gastroenterology best practices.\n\n**Who it's for:** Children aged 2-3 years developing independent eating skills.",
        creator: "AAP early childhood nutrition", source: "AAP early childhood nutrition", evidence: "moderate", score: 88,
        items: [
          { name: "Breakfast", item_type: "consume", meta: "07:00" },
          { name: "Outdoor Play", item_type: "activity", meta: "09:00" },
          { name: "Morning Snack", item_type: "consume", meta: "10:00" },
          { name: "Lunch", item_type: "consume", meta: "12:00" },
          { name: "Afternoon Snack", item_type: "consume", meta: "15:00" },
          { name: "Creative Play", item_type: "activity", meta: "16:00" },
          { name: "Dinner", item_type: "consume", meta: "17:30" },
          { name: "Multivitamin Gummy", item_type: "supplement", meta: "18:00" },
        ],
      },
      {
        key: "toddler-nutrition-1-to-2-years", name: "Toddler Nutrition — 1 to 2 Years", chip: "Ages 1–2",
        description: "Transition from baby foods to family meals. Focus on balanced nutrition, self-feeding skills, and establishing healthy eating patterns during this critical growth phase.\n\n**What it does to the body:**\n• Whole milk provides 8g protein and 300mg calcium per cup — critical for the 50% bone mass increase that occurs between ages 1-3.\n• Iron-rich foods (red meat, lentils, fortified cereals) prevent the iron deficiency that affects 7-9% of toddlers, which can cause irreversible cognitive delays.\n• Self-feeding with finger foods develops fine motor coordination (pincer grip) and builds neural pathways for hand-eye coordination.\n• Repeated exposure to new foods (10-15 times) reduces neophobia — toddlers naturally reject unfamiliar foods as an evolutionary protective mechanism.\n• Active play for 30+ minutes daily builds gross motor skills, supports healthy weight trajectory, and improves sleep consolidation.\n• Vitamin D (400-600 IU) continues to be essential as toddlers transition off fortified formula, supporting immune cell maturation and calcium absorption.\n\n**Who created it:** Based on AAP toddler nutrition guidelines, WHO complementary feeding recommendations, and Ellyn Satter's Division of Responsibility in Feeding.\n\n**Who it's for:** Children aged 1-2 years transitioning to family meals. Adjust portions and textures based on individual development.",
        creator: "AAP toddler nutrition guidelines", source: "AAP toddler nutrition guidelines", evidence: "moderate", score: 90,
        items: [
          { name: "Whole Milk", item_type: "consume", meta: "07:00" },
          { name: "Active Play", item_type: "activity", meta: "09:00" },
          { name: "Morning Snack", item_type: "consume", meta: "10:00" },
          { name: "Lunch", item_type: "consume", meta: "12:00" },
          { name: "Afternoon Snack", item_type: "consume", meta: "15:00" },
          { name: "Dinner", item_type: "consume", meta: "17:30" },
          { name: "Vitamin D", item_type: "supplement", meta: "18:00" },
          { name: "Bedtime Milk", item_type: "consume", meta: "19:00" },
        ],
      },
    ],
  },
  {
    key: "longevity", label: "Longevity", pillar: "Health",
    protocols: [
      {
        key: "self-heal-by-design", name: "Self Heal by Design", chip: "Self Heal by Design",
        description: "Barbara O'Neill's flagship full-day protocol from her 2014 book \"Self Heal by Design\" — the complete natural-healing routine that built her reputation across Australia and the United States.\n\n### The daily rhythm\nMorning sun for circadian entrainment, 16:8 intermittent fasting, raw fruits and vegetables as the foundation of every meal, deep hydration with mineralised water, daily movement and barefoot grounding, and consistent sleep hygiene.\n\n### The 8 Laws of Health\n**Nutrition · exercise · water · sunlight · temperance · air · rest · trust.** This is the umbrella protocol every other Barbara routine sits inside.\n\n### Why it matters\nA single integrated daily rhythm is more sustainable than chasing individual interventions — Barbara's tens of thousands of retreat alumni use this as their lifelong template.\n\nSource: Self Heal by Design (book). Educational lifestyle content reflecting Barbara O'Neill's published teachings — not medical advice.",
        creator: "Barbara O'Neill", source: "Barbara O'Neill — Self Heal by Design", evidence: "moderate", score: 88,
        items: [
          { name: "Gratitude on Waking", item_type: "activity", meta: "05:30" },
          { name: "Tongue Scraping", item_type: "activity", meta: "05:35" },
          { name: "Warm Lemon Water", item_type: "consume", meta: "05:40" },
          { name: "Apple Cider Vinegar Tonic", item_type: "supplement", meta: "05:50" },
          { name: "Oil Pulling", item_type: "activity", meta: "06:00" },
          { name: "Dry Skin Brushing", item_type: "activity", meta: "06:15" },
          { name: "Hot/Cold Contrast Shower", item_type: "activity", meta: "06:20" },
          { name: "Barefoot Grounding", item_type: "activity", meta: "06:30" },
          { name: "Morning Sunlight", item_type: "activity", meta: "06:35" },
          { name: "4-7-8 Breathing", item_type: "activity", meta: "06:55" },
          { name: "Rebounding", item_type: "activity", meta: "07:00" },
          { name: "Spinal Mobility", item_type: "activity", meta: "07:15" },
          { name: "Beetroot", item_type: "consume", meta: "07:30" },
          { name: "Freshly Ground Flaxseed", item_type: "supplement", meta: "07:45" },
          { name: "Soaked Oats with Berries, Flax & Raw Honey", item_type: "consume", meta: "08:00" },
          { name: "Brisk Walk After Breakfast", item_type: "activity", meta: "08:35" },
          { name: "Meditation", item_type: "activity", meta: "09:00" },
          { name: "Big Rainbow Salad with Sprouts", item_type: "consume", meta: "12:30" },
          { name: "Brisk Walk After Lunch", item_type: "activity", meta: "13:15" },
          { name: "Midday Sun for Vitamin D", item_type: "activity", meta: "14:00" },
          { name: "Daily Nature Time", item_type: "activity", meta: "15:00" },
          { name: "Infrared / Steam Sauna", item_type: "activity", meta: "16:00" },
          { name: "Daily Outdoor Walk", item_type: "activity", meta: "17:00" },
          { name: "Sleep in Complete Darkness", item_type: "activity", meta: "22:00" },
        ],
      },
      {
        key: "dr-rhonda-patrick-micronutrient-protocol", name: "Dr. Rhonda Patrick Micronutrient Protocol", chip: "Rhonda Patrick",
        description: "FoundMyFitness scientist's evidence-backed longevity stack. Daily sauna 20 min at 80°C (4x/week), cold plunge immediately after, omega-3 4g EPA+DHA, vitamin D3 5000 IU + K2, magnesium glycinate 400mg, sulforaphane from broccoli sprouts, and quarterly comprehensive blood panels. Exercise 5x/week, prioritise sleep 7-9 hrs.",
        creator: "Rhonda Patrick", evidence: "high", score: 93,
        items: [
          { name: "Omega-3 Fish Oil", item_type: "supplement", meta: "07:00" },
          { name: "Vitamin D3", item_type: "supplement", meta: "07:02" },
          { name: "Magnesium Bisglycinate", item_type: "supplement", meta: "07:03" },
          { name: "Sulforaphane via Broccoli Sprouts", item_type: "consume", meta: "07:10" },
          { name: "Vitamin C", item_type: "supplement", meta: "07:15" },
          { name: "B-Complex", item_type: "supplement", meta: "07:16" },
          { name: "Sauna Session", item_type: "activity", meta: "10:00" },
          { name: "Cold Plunge Immersion", item_type: "activity", meta: "10:25" },
          { name: "Rehydration", item_type: "consume", meta: "10:30" },
          { name: "Zone 2 Cardio", item_type: "activity", meta: "11:00" },
          { name: "Micronutrient Blood Panel Review", item_type: "activity", meta: "18:00" },
          { name: "Polyphenol-Rich Dinner", item_type: "consume", meta: "19:00" },
          { name: "Melatonin", item_type: "supplement", meta: "21:00" },
          { name: "Selenium", item_type: "supplement", meta: "21:02" },
          { name: "Sleep", item_type: "activity", meta: "21:30" },
        ],
      },
      {
        key: "longevity-inspired-by-bryan-johnson", name: "Longevity — Inspired by Bryan Johnson", chip: "Bryan Johnson",
        description: "A structured morning routine built around well-known healthspan habits: early light exposure, a polyphenol-rich pre-workout drink, a consistent daily supplement stack, exercise on a rotating 7-day plan, and a nutrient-dense breakfast.\n\nThe goal is a repeatable, evidence-informed morning rhythm — circadian light, movement, and whole-food nutrition — that supports general energy and wellbeing.\n\nThis routine reflects healthspan principles popularised by Bryan Johnson's Blueprint project. So Health is not affiliated with, endorsed by, or sponsored by Bryan Johnson or Blueprint. Educational lifestyle content — not medical advice.",
        creator: "Bryan Johnson", source: "Longevity Morning Protocol — reflecting healthspan principles popularised by Bryan Johnson's Blueprint project. Not affiliated with, endorsed by, or sponsored by Bryan Johnson or Blueprint. Educational content, not medical advice.", evidence: "moderate", days: 7, score: 97,
        items: [
          { name: "Body Composition", item_type: "activity", meta: "05:00" },
          { name: "Wake Up", item_type: "activity", meta: "05:00" },
          { name: "Morning Mindfulness", item_type: "activity", meta: "05:00" },
          { name: "Light Exposure", item_type: "activity", meta: "05:05" },
          { name: "Hair Care Routine", item_type: "activity", meta: "05:09" },
          { name: "Quick Shower", item_type: "activity", meta: "05:20" },
          { name: "Pre-Workout Longevity Drink", item_type: "consume", meta: "05:25" },
          { name: "Nr or Nmn", item_type: "supplement", meta: "05:35" },
          { name: "Proferrin", item_type: "supplement", meta: "05:35" },
          { name: "Pre-Workout Breakfast", item_type: "consume", meta: "05:35" },
          { name: "Omega-3", item_type: "supplement", meta: "05:35" },
          { name: "Advanced Antioxidants", item_type: "supplement", meta: "05:35" },
          { name: "Essential Capsules", item_type: "supplement", meta: "05:35" },
          { name: "Ashwagandha", item_type: "supplement", meta: "05:35" },
          { name: "Dynamic Stretching", item_type: "activity", meta: "06:00" },
          { name: "Hiit", item_type: "activity", meta: "06:00" },
          { name: "Active Recovery", item_type: "activity", meta: "06:00" },
          { name: "Gentle Yoga/stretching", item_type: "activity", meta: "06:00" },
          { name: "Strength Focus", item_type: "activity", meta: "06:00" },
          { name: "Strength", item_type: "activity", meta: "06:00" },
          { name: "Norwegian 4x4", item_type: "activity", meta: "06:00" },
          { name: "HIIT", item_type: "activity", meta: "06:00" },
          { name: "General Warm-Up", item_type: "activity", meta: "06:00" },
          { name: "Evening Sleep Start", item_type: "activity", meta: "20:30" },
        ],
      },
    ],
  },
];
