/**
 * Risk categories for the hazardous elements editor.
 * Each category groups elements from catalog_elements by their risk pathway.
 * Data format stored in elements_hazardous: { [element_id]: level }
 * where level is 'none' | 'trace' | 'low' | 'moderate' | 'high'
 */

export interface RiskElement {
  id: string;
  name_common: string;
  category: string;
}

export interface RiskCategory {
  key: string;
  label: string;
  icon: string;
  color: string;
  elements: RiskElement[];
}

export const RISK_CATEGORIES: RiskCategory[] = [
  {
    key: 'environmental_contamination',
    label: 'Environmental contamination (air, water, soil, packaging)',
    icon: '🏭',
    color: 'orange',
    elements: [
      { id: '1_3_butadiene', name_common: '1,3-Butadiene', category: 'voc' },
      { id: '1_4_dioxane', name_common: '1,4-Dioxane', category: 'industrial' },
      { id: 'acetaldehyde', name_common: 'Acetaldehyde', category: 'voc' },
      { id: 'acrolein', name_common: 'Acrolein', category: 'voc' },
      { id: 'antimony', name_common: 'Antimony', category: 'heavy_metal' },
      { id: 'benzene', name_common: 'Benzene', category: 'voc' },
      { id: 'benzyl_butyl_phthalate', name_common: 'Benzyl butyl phthalate', category: 'plasticizer' },
      { id: 'bisphenol_a', name_common: 'Bisphenol A', category: 'plasticizer' },
      { id: 'bisphenol_f', name_common: 'Bisphenol F', category: 'plasticizer' },
      { id: 'bisphenol_s', name_common: 'Bisphenol S', category: 'plasticizer' },
      { id: 'cadmium', name_common: 'Cadmium', category: 'heavy metal' },
      { id: 'carbon_disulfide', name_common: 'Carbon Disulfide', category: 'industrial' },
      { id: 'carbon_monoxide', name_common: 'Carbon Monoxide', category: 'environment' },
      { id: 'chloroform', name_common: 'Chloroform', category: 'voc' },
      { id: 'chromium_vi', name_common: 'Chromium VI', category: 'heavy metal' },
      { id: 'dbp', name_common: 'DBP', category: 'plasticizer' },
      { id: 'dehp', name_common: 'DEHP', category: 'plasticizer' },
      { id: 'dichloromethane', name_common: 'Dichloromethane', category: 'industrial' },
      { id: 'didp', name_common: 'DIDP', category: 'plasticizer' },
      { id: 'dimethylformamide', name_common: 'Dimethylformamide', category: 'industrial' },
      { id: 'dinp', name_common: 'DINP', category: 'plasticizer' },
      { id: 'dioxins_tcdd', name_common: 'Dioxins (TCDD)', category: 'industrial' },
      { id: 'epichlorohydrin', name_common: 'Epichlorohydrin', category: 'industrial' },
      { id: 'ethylbenzene', name_common: 'Ethylbenzene', category: 'voc' },
      { id: 'ethylene_oxide', name_common: 'Ethylene Oxide', category: 'industrial' },
      { id: 'formaldehyde', name_common: 'Formaldehyde', category: 'voc' },
      { id: 'furans', name_common: 'Furans', category: 'industrial' },
      { id: 'genx_pfoa_replacement', name_common: 'GenX (PFOA Replacement)', category: 'pfas' },
      { id: 'ground_level_ozone', name_common: 'Ground-level Ozone', category: 'environment' },
      { id: 'hexachlorobenzene', name_common: 'Hexachlorobenzene', category: 'industrial' },
      { id: 'lead', name_common: 'Lead', category: 'heavy metal' },
      { id: 'melamine', name_common: 'Melamine', category: 'industrial' },
      { id: 'mercury', name_common: 'Mercury', category: 'heavy metal' },
      { id: 'methyl_ethyl_ketone', name_common: 'Methyl Ethyl Ketone', category: 'industrial' },
      { id: 'methylene_chloride', name_common: 'Methylene Chloride', category: 'voc' },
      { id: 'microplastics', name_common: 'Microplastics', category: 'industrial' },
      { id: 'mycotoxins', name_common: 'mycotoxins', category: 'hazardous_element' },
      { id: 'nanomaterials', name_common: 'Nanomaterials', category: 'industrial' },
      { id: 'nitrogen_dioxide', name_common: 'Nitrogen Dioxide', category: 'environment' },
      { id: 'nonylphenol', name_common: 'Nonylphenol', category: 'plasticizer' },
      { id: 'pahs', name_common: 'pahs', category: 'hazardous_element' },
      { id: 'pbdes', name_common: 'PBDEs', category: 'industrial' },
      { id: 'pcbs', name_common: 'PCBs', category: 'industrial' },
      { id: 'perchlorate', name_common: 'Perchlorate', category: 'industrial' },
      { id: 'perchloroethylene', name_common: 'Perchloroethylene', category: 'industrial' },
      { id: 'pfas', name_common: 'pfas', category: 'hazardous_element' },
      { id: 'pfbs', name_common: 'PFBS', category: 'pfas' },
      { id: 'pfda', name_common: 'PFDA', category: 'pfas' },
      { id: 'pfdoda', name_common: 'PFDoDA', category: 'pfas' },
      { id: 'pfhpa', name_common: 'PFHpA', category: 'pfas' },
      { id: 'pfhxs', name_common: 'PFHxS', category: 'pfas' },
      { id: 'pfna', name_common: 'PFNA', category: 'pfas' },
      { id: 'pfoa', name_common: 'PFOA', category: 'industrial' },
      { id: 'pfos', name_common: 'PFOS', category: 'pfas' },
      { id: 'pfunda', name_common: 'PFUnDA', category: 'pfas' },
      { id: 'pm10', name_common: 'PM10', category: 'environment' },
      { id: 'pm2_5', name_common: 'PM2.5', category: 'environment' },
      { id: 'polycyclic_oil_mist', name_common: 'Polycyclic Oil Mist', category: 'industrial' },
      { id: 'propylene_oxide', name_common: 'Propylene Oxide', category: 'industrial' },
      { id: 'residual_formaldehyde', name_common: 'Residual Formaldehyde', category: 'industrial' },
      { id: 'styrene', name_common: 'Styrene', category: 'voc' },
      { id: 'sulfur_dioxide', name_common: 'Sulfur Dioxide', category: 'environment' },
      { id: 'tetrachloroethane', name_common: 'Tetrachloroethane', category: 'industrial' },
      { id: 'tetrachloroethylene', name_common: 'Tetrachloroethylene', category: 'voc' },
      { id: 'thallium', name_common: 'Thallium', category: 'heavy metal' },
      { id: 'toluene', name_common: 'Toluene', category: 'voc' },
      { id: 'tributyltin', name_common: 'Tributyltin', category: 'industrial' },
      { id: 'trichlorobenzene', name_common: 'Trichlorobenzene', category: 'industrial' },
      { id: 'trichloroethylene', name_common: 'Trichloroethylene', category: 'voc' },
      { id: 'triphenyl_phosphate', name_common: 'Triphenyl phosphate', category: 'plasticizer' },
      { id: 'uranium', name_common: 'Uranium', category: 'contaminant' },
      { id: 'vinyl_acetate', name_common: 'Vinyl Acetate', category: 'industrial' },
      { id: 'vinyl_chloride', name_common: 'Vinyl Chloride', category: 'voc' },
      { id: 'xylene', name_common: 'Xylene', category: 'voc' },
    ],
  },
  {
    key: 'farming_chemicals',
    label: 'Farming chemicals (crop residues)',
    icon: '🌾',
    color: 'orange',
    elements: [
      { id: '2_4_d', name_common: '2,4-D', category: 'pesticide' },
      { id: 'aldicarb', name_common: 'Aldicarb', category: 'pesticide' },
      { id: 'aldrin', name_common: 'Aldrin', category: 'pesticide' },
      { id: 'atrazine', name_common: 'Atrazine', category: 'pesticide' },
      { id: 'carbaryl', name_common: 'Carbaryl', category: 'pesticide' },
      { id: 'carbofuran', name_common: 'Carbofuran', category: 'pesticide' },
      { id: 'chlordane', name_common: 'Chlordane', category: 'pesticide' },
      { id: 'chlorpyrifos', name_common: 'Chlorpyrifos', category: 'pesticide' },
      { id: 'clothianidin', name_common: 'Clothianidin', category: 'pesticide' },
      { id: 'cypermethrin', name_common: 'Cypermethrin', category: 'pesticide' },
      { id: 'ddt', name_common: 'DDT', category: 'pesticide' },
      { id: 'diazinon', name_common: 'Diazinon', category: 'pesticide' },
      { id: 'dicamba', name_common: 'Dicamba', category: 'pesticide' },
      { id: 'dieldrin', name_common: 'Dieldrin', category: 'pesticide' },
      { id: 'endosulfan', name_common: 'Endosulfan', category: 'pesticide' },
      { id: 'fipronil', name_common: 'Fipronil', category: 'pesticide' },
      { id: 'glyphosate', name_common: 'Glyphosate', category: 'pesticide' },
      { id: 'heptachlor', name_common: 'Heptachlor', category: 'pesticide' },
      { id: 'imidacloprid', name_common: 'Imidacloprid', category: 'pesticide' },
      { id: 'lindane', name_common: 'Lindane', category: 'pesticide' },
      { id: 'malathion', name_common: 'Malathion', category: 'pesticide' },
      { id: 'methamidophos', name_common: 'Methamidophos', category: 'pesticide' },
      { id: 'methomyl', name_common: 'Methomyl', category: 'pesticide' },
      { id: 'methyl_parathion', name_common: 'Methyl Parathion', category: 'pesticide' },
      { id: 'monocrotophos', name_common: 'Monocrotophos', category: 'pesticide' },
      { id: 'neonicotinoids', name_common: 'Neonicotinoids', category: 'pesticide' },
      { id: 'paraquat', name_common: 'Paraquat', category: 'pesticide' },
      { id: 'parathion', name_common: 'Parathion', category: 'pesticide' },
      { id: 'permethrin', name_common: 'Permethrin', category: 'pesticide' },
      { id: 'thiamethoxam', name_common: 'Thiamethoxam', category: 'pesticide' },
    ],
  },
  {
    key: 'ingredients_formulation',
    label: 'Ingredients & formulation (added to products)',
    icon: '🧪',
    color: 'orange',
    elements: [
      { id: 'acesulfame_potassium', name_common: 'Acesulfame Potassium', category: 'additive' },
      { id: 'advantame', name_common: 'Advantame', category: 'additive' },
      { id: 'allura_red_ac', name_common: 'Allura Red AC', category: 'additive' },
      { id: 'amaranth', name_common: 'Amaranth', category: 'additive' },
      { id: 'aspartame', name_common: 'Aspartame', category: 'additive' },
      { id: 'azodicarbonamide', name_common: 'Azodicarbonamide', category: 'additive' },
      { id: 'brilliant_blue', name_common: 'Brilliant Blue', category: 'additive' },
      { id: 'brown_ht', name_common: 'Brown HT', category: 'additive' },
      { id: 'bha_butylated_hydroxyanisole', name_common: 'Butylated Hydroxyanisole (BHA)', category: 'additive' },
      { id: 'bht_butylated_hydroxytoluene', name_common: 'Butylated Hydroxytoluene (BHT)', category: 'additive' },
      { id: 'caffeine', name_common: 'Caffeine', category: 'stimulant' },
      { id: 'calcium_propionate', name_common: 'Calcium Propionate', category: 'additive' },
      { id: 'caramel_color', name_common: 'Caramel Color', category: 'additive' },
      { id: 'carmine', name_common: 'Carmine', category: 'additive' },
      { id: 'carrageenan', name_common: 'Carrageenan', category: 'additive' },
      { id: 'erythrosine', name_common: 'Erythrosine', category: 'additive' },
      { id: 'ethanol', name_common: 'Ethanol', category: 'alcohol' },
      { id: 'glycerol', name_common: 'Glycerol (Glycerin)', category: 'additive' },
      { id: 'green_s', name_common: 'Green S', category: 'additive' },
      { id: 'guar_gum', name_common: 'Guar Gum', category: 'additive' },
      { id: 'high_fructose_corn_syrup', name_common: 'High Fructose Corn Syrup', category: 'sugar' },
      { id: 'indigotine', name_common: 'Indigotine', category: 'additive' },
      { id: 'invert_sugar', name_common: 'Invert Sugar', category: 'sugar' },
      { id: 'isomalt', name_common: 'Isomalt', category: 'food additive' },
      { id: 'malic_acid', name_common: 'Malic Acid', category: 'additive' },
      { id: 'maltitol', name_common: 'Maltitol', category: 'food additive' },
      { id: 'maltodextrin', name_common: 'Maltodextrin', category: 'sugar' },
      { id: 'mannitol', name_common: 'Mannitol', category: 'artificial sweetener' },
      { id: 'monoglycerides', name_common: 'Monoglycerides', category: 'additive' },
      { id: 'neotame', name_common: 'Neotame', category: 'additive' },
      { id: 'polyglycerol_esters_of_fatty_acids', name_common: 'Polyglycerol Esters of Fatty Acids', category: 'additive' },
      { id: 'polysorbate_60', name_common: 'Polysorbate 60', category: 'additive' },
      { id: 'polysorbate_80', name_common: 'Polysorbate 80', category: 'additive' },
      { id: 'ponceau_4r', name_common: 'Ponceau 4R', category: 'additive' },
      { id: 'potassium_bromate', name_common: 'Potassium Bromate', category: 'additive' },
      { id: 'potassium_sorbate', name_common: 'Potassium Sorbate', category: 'additive' },
      { id: 'saccharin', name_common: 'Saccharin', category: 'additive' },
      { id: 'sodium_benzoate', name_common: 'Sodium Benzoate', category: 'additive' },
      { id: 'sodium_metabisulfite', name_common: 'Sodium Metabisulfite', category: 'additive' },
      { id: 'sodium_nitrate', name_common: 'Sodium Nitrate', category: 'additive' },
      { id: 'sodium_nitrite', name_common: 'Sodium Nitrite', category: 'additive' },
      { id: 'sorbitol', name_common: 'Sorbitol', category: 'artificial_sweetener' },
      { id: 'sucralose', name_common: 'Sucralose', category: 'additive' },
      { id: 'sunset_yellow', name_common: 'Sunset Yellow', category: 'additive' },
      { id: 'tartrazine', name_common: 'Tartrazine', category: 'additive' },
      { id: 'tbhq_tertiary_butylhydroquinone', name_common: 'Tertiary-Butylhydroquinone (TBHQ)', category: 'additive' },
      { id: 'theobromine', name_common: 'Theobromine', category: 'stimulant' },
      { id: 'titanium_dioxide', name_common: 'Titanium Dioxide', category: 'additive' },
      { id: 'xanthan_gum', name_common: 'Xanthan Gum', category: 'additive' },
      { id: 'xylitol', name_common: 'Xylitol', category: 'artificial_sweetener' },
    ],
  },
  {
    key: 'processing_cooking_byproducts',
    label: 'Processing & cooking byproducts',
    icon: '🔥',
    color: 'orange',
    elements: [
      { id: 'acrylamide', name_common: 'Acrylamide', category: 'industrial' },
      { id: 'anthracene', name_common: 'Anthracene', category: 'pah' },
      { id: 'benzo_a_pyrene', name_common: 'Benzo(a)pyrene', category: 'pah' },
      { id: 'benzo_b_fluoranthene', name_common: 'Benzo(b)fluoranthene', category: 'pah' },
      { id: 'benzo_k_fluoranthene', name_common: 'Benzo(k)fluoranthene', category: 'pah' },
      { id: 'dibenz_a_h_anthracene', name_common: 'Dibenz(a,h)anthracene', category: 'pah' },
      { id: 'fluoranthene', name_common: 'Fluoranthene', category: 'pah' },
      { id: 'indeno_1_2_3_cd_pyrene', name_common: 'Indeno(1,2,3-cd)pyrene', category: 'pah' },
      { id: 'naphthalene', name_common: 'Naphthalene', category: 'pah' },
      { id: 'nitrosamines', name_common: 'Nitrosamines', category: 'industrial' },
      { id: 'phenanthrene', name_common: 'Phenanthrene', category: 'pah' },
      { id: 'pyrene', name_common: 'Pyrene', category: 'pah' },
    ],
  },
  {
    key: 'storage_spoilage',
    label: 'Storage & spoilage (mold toxins)',
    icon: '🧫',
    color: 'orange',
    elements: [
      { id: 'aflatoxin_b1', name_common: 'Aflatoxin B1', category: 'mycotoxin' },
      { id: 'citrinin', name_common: 'Citrinin', category: 'mycotoxin' },
      { id: 'deoxynivalenol', name_common: 'Deoxynivalenol', category: 'mycotoxin' },
      { id: 'ergot_alkaloids', name_common: 'Ergot Alkaloids', category: 'mycotoxin' },
      { id: 'fumonisin_b1', name_common: 'Fumonisin B1', category: 'mycotoxin' },
      { id: 'nivalenol', name_common: 'Nivalenol', category: 'mycotoxin' },
      { id: 'ochratoxin_a', name_common: 'Ochratoxin A', category: 'mycotoxin' },
      { id: 'patulin', name_common: 'Patulin', category: 'mycotoxin' },
      { id: 't_2_toxin', name_common: 'T-2 Toxin', category: 'mycotoxin' },
      { id: 'zearalenone', name_common: 'Zearalenone', category: 'mycotoxin' },
    ],
  },
  {
    key: 'microorganisms',
    label: 'Microorganisms (bacteria, viruses, parasites)',
    icon: '🦠',
    color: 'green',
    elements: [
      { id: 'adenovirus', name_common: 'Adenovirus', category: 'virus' },
      { id: 'anisakis_simplex', name_common: 'Anisakis simplex', category: 'parasite' },
      { id: 'ascaris_lumbricoides', name_common: 'Ascaris lumbricoides', category: 'parasite' },
      { id: 'astrovirus', name_common: 'astrovirus', category: 'virus' },
      { id: 'bacillus_cereus', name_common: 'Bacillus cereus', category: 'bacteria' },
      { id: 'campylobacter_jejuni', name_common: 'Campylobacter jejuni', category: 'bacteria' },
      { id: 'clonorchis_sinensis', name_common: 'Clonorchis sinensis', category: 'parasite' },
      { id: 'clostridium_botulinum', name_common: 'Clostridium botulinum', category: 'bacteria' },
      { id: 'clostridium_perfringens', name_common: 'Clostridium perfringens', category: 'bacteria' },
      { id: 'cronobacter_sakazakii', name_common: 'Cronobacter sakazakii', category: 'bacteria' },
      { id: 'cryptosporidium_parvum', name_common: 'Cryptosporidium parvum', category: 'parasite' },
      { id: 'cyclospora_cayetanensis', name_common: 'Cyclospora cayetanensis', category: 'parasite' },
      { id: 'diphyllobothrium_latum', name_common: 'Diphyllobothrium latum', category: 'parasite' },
      { id: 'e_coli_o157_h7', name_common: 'E. coli', category: 'bacteria' },
      { id: 'echinococcus_granulosus', name_common: 'Echinococcus granulosus', category: 'parasite' },
      { id: 'entamoeba_histolytica', name_common: 'Entamoeba histolytica', category: 'parasite' },
      { id: 'fasciola_hepatica', name_common: 'Fasciola hepatica', category: 'parasite' },
      { id: 'giardia_lamblia', name_common: 'Giardia lamblia', category: 'parasite' },
      { id: 'hepatitis_a_virus', name_common: 'Hepatitis A Virus', category: 'virus' },
      { id: 'hepatitis_e', name_common: 'Hepatitis E', category: 'virus' },
      { id: 'influenza_a', name_common: 'influenza a', category: 'virus' },
      { id: 'influenza_b', name_common: 'influenza b', category: 'virus' },
      { id: 'listeria_monocytogenes', name_common: 'Listeria monocytogenes', category: 'bacteria' },
      { id: 'measles', name_common: 'measles', category: 'virus' },
      { id: 'norovirus', name_common: 'Norovirus', category: 'virus' },
      { id: 'poliovirus', name_common: 'Poliovirus', category: 'virus' },
      { id: 'rotavirus', name_common: 'Rotavirus', category: 'virus' },
      { id: 'salmonella', name_common: 'Salmonella', category: 'bacteria' },
      { id: 'salmonella_enteritidis', name_common: 'Salmonella Enteritidis', category: 'bacteria' },
      { id: 'sapovirus', name_common: 'sapovirus', category: 'virus' },
      { id: 'sars_cov_2', name_common: 'sars cov 2', category: 'virus' },
      { id: 'schistosoma_mansoni', name_common: 'Schistosoma mansoni', category: 'parasite' },
      { id: 'shigella_dysenteriae', name_common: 'Shigella dysenteriae', category: 'bacteria' },
      { id: 'staphylococcus_aureus', name_common: 'Staphylococcus aureus', category: 'bacteria' },
      { id: 'strongyloides_stercoralis', name_common: 'Strongyloides stercoralis', category: 'parasite' },
      { id: 'taenia_saginata', name_common: 'Taenia saginata', category: 'parasite' },
      { id: 'taenia_solium', name_common: 'Taenia solium', category: 'parasite' },
      { id: 'toxoplasma_gondii', name_common: 'Toxoplasma gondii', category: 'parasite' },
      { id: 'trichinella_spiralis', name_common: 'Trichinella spiralis', category: 'parasite' },
      { id: 'vibrio_cholerae', name_common: 'Vibrio cholerae', category: 'bacteria' },
      { id: 'vibrio_parahaemolyticus', name_common: 'Vibrio parahaemolyticus', category: 'bacteria' },
      { id: 'yersinia_enterocolitica', name_common: 'Yersinia enterocolitica', category: 'bacteria' },
    ],
  },
  {
    key: 'veterinary_drugs_hormones',
    label: 'Veterinary drugs, hormones & antibiotics (animal farming)',
    icon: '💉',
    color: 'orange',
    elements: [
      { id: 'rbgh_rbst', name_common: 'rBGH / rBST (Bovine Growth Hormone)', category: 'hormone' },
      { id: 'estradiol', name_common: 'Estradiol (17β-Estradiol)', category: 'hormone' },
      { id: 'zeranol', name_common: 'Zeranol', category: 'hormone' },
      { id: 'trenbolone_acetate', name_common: 'Trenbolone Acetate', category: 'hormone' },
      { id: 'melengestrol_acetate', name_common: 'Melengestrol Acetate', category: 'hormone' },
      { id: 'progesterone', name_common: 'Progesterone', category: 'hormone' },
      { id: 'testosterone', name_common: 'Testosterone', category: 'hormone' },
      { id: 'igf_1', name_common: 'IGF-1 (Insulin-like Growth Factor)', category: 'hormone' },
      { id: 'ractopamine', name_common: 'Ractopamine', category: 'growth_promoter' },
      { id: 'clenbuterol', name_common: 'Clenbuterol', category: 'growth_promoter' },
      { id: 'tetracycline', name_common: 'Tetracycline', category: 'antibiotic' },
      { id: 'oxytetracycline', name_common: 'Oxytetracycline', category: 'antibiotic' },
      { id: 'amoxicillin', name_common: 'Amoxicillin', category: 'antibiotic' },
      { id: 'sulfamethazine', name_common: 'Sulfamethazine', category: 'antibiotic' },
      { id: 'enrofloxacin', name_common: 'Enrofloxacin', category: 'antibiotic' },
      { id: 'chloramphenicol', name_common: 'Chloramphenicol', category: 'antibiotic' },
      { id: 'florfenicol', name_common: 'Florfenicol', category: 'antibiotic' },
      { id: 'erythromycin', name_common: 'Erythromycin', category: 'antibiotic' },
      { id: 'emamectin_benzoate', name_common: 'Emamectin Benzoate (sea lice treatment)', category: 'aquaculture' },
      { id: 'malachite_green', name_common: 'Malachite Green', category: 'aquaculture' },
      { id: 'ethoxyquin', name_common: 'Ethoxyquin (feed antioxidant)', category: 'aquaculture' },
      { id: 'synthetic_astaxanthin', name_common: 'Synthetic Astaxanthin (feed colorant)', category: 'aquaculture' },
      { id: 'diflubenzuron', name_common: 'Diflubenzuron (sea lice treatment)', category: 'aquaculture' },
      { id: 'ivermectin', name_common: 'Ivermectin', category: 'antiparasitic' },
      { id: 'fenbendazole', name_common: 'Fenbendazole', category: 'antiparasitic' },
    ],
  },
  {
    key: 'natural_food_compounds',
    label: 'Natural food compounds (plant toxins / antinutrients)',
    icon: '🌿',
    color: 'orange',
    elements: [
      { id: 'ciguatoxin', name_common: 'Ciguatoxin', category: 'plant_toxin' },
      { id: 'goitrogens', name_common: 'Goitrogens', category: 'plant toxin' },
      { id: 'grayanotoxins', name_common: 'Grayanotoxins', category: 'plant_toxin' },
      { id: 'hypoglycin_a', name_common: 'Hypoglycin A', category: 'plant toxin' },
      { id: 'lectins', name_common: 'Lectins', category: 'plant_toxin' },
      { id: 'oxalates', name_common: 'Oxalates', category: 'plant_toxin' },
      { id: 'phytates', name_common: 'Phytates', category: 'plant toxin' },
      { id: 'pyrrolizidine_alkaloids', name_common: 'Pyrrolizidine Alkaloids', category: 'plant_toxin' },
      { id: 'sambunigrin', name_common: 'Sambunigrin', category: 'plant_toxin' },
      { id: 'saponins', name_common: 'Saponins', category: 'plant_toxin' },
      { id: 'saxitoxin', name_common: 'Saxitoxin', category: 'plant toxin' },
      { id: 'solanine', name_common: 'Solanine', category: 'plant_toxin' },
      { id: 'tannins', name_common: 'Tannins', category: 'plant toxin' },
      { id: 'tetrodotoxin', name_common: 'Tetrodotoxin', category: 'plant_toxin' },
    ],
  },
];

export const HAZARD_LEVELS = ['none', 'trace', 'low', 'moderate', 'high'] as const;
export type HazardLevel = typeof HAZARD_LEVELS[number];

export const HAZARD_LEVEL_COLORS: Record<string, string> = {
  none: 'bg-gray-100 text-gray-500 border-gray-200',
  trace: 'bg-orange-50 text-orange-600 border-orange-200',
  low: 'bg-orange-100 text-orange-700 border-orange-300',
  moderate: 'bg-orange-200 text-orange-800 border-orange-400',
  high: 'bg-orange-300 text-orange-900 border-orange-500',
};

export const CATEGORY_HEADER_COLORS: Record<string, string> = {
  orange: 'text-orange-600 bg-orange-50 border-orange-200',
  green: 'text-green-600 bg-green-50 border-green-200',
};
