/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mofhvoudjxinvpplsytd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vZmh2b3VkanhpbnZwcGxzeXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NDM5MjAsImV4cCI6MjA1NjAxOTkyMH0.zZWhLMur9uKko-3PSQp3aRoMvOt0Ig-GzBsMblelAp0"