/*
 * Supabase connection info — ENVIRONMENT-AWARE.
 *
 * This used to be an autogenerated file hardcoded to a single project.
 * It now derives projectId / publicAnonKey from the environment selected in
 * the admin Environment switch (staging | production).
 *
 * - Selection is persisted in localStorage ('supabase-environment') and
 *   defaults to 'staging' (see ./environments.ts).
 * - Switching environments triggers a full page reload, so reading the
 *   selection once at module load is consistent across the whole app.
 *
 * Every consumer that imports { projectId, publicAnonKey } from './info'
 * now automatically follows the selected environment.
 *
 * NOTE: if this project is ever re-exported from Figma Make, the generator may
 * overwrite this file back to hardcoded values — re-apply this wrapper if so.
 */
import { getCurrentEnvironmentConfig } from './environments';

const config = getCurrentEnvironmentConfig();

export const projectId = config.projectId;
export const publicAnonKey = config.publicAnonKey;
