-- Fix hs_supplements schema and seed data
-- Add missing columns
ALTER TABLE hs_supplements ADD COLUMN IF NOT EXISTS supplier_website TEXT;
ALTER TABLE hs_supplements ADD COLUMN IF NOT EXISTS supplier_email TEXT;
ALTER TABLE hs_supplements ADD COLUMN IF NOT EXISTS link_type TEXT;
ALTER TABLE hs_supplements ADD COLUMN IF NOT EXISTS shopify_product_url TEXT;
ALTER TABLE hs_supplements ADD COLUMN IF NOT EXISTS shopify_product_id TEXT;

-- Seed Essential 90 supplements with supplier logos, costs, and margins
INSERT INTO hs_supplements (slug, name, element_key, category, region, currency, retail_price, estimated_cost, margin_pct, supplier, supplier_website, supplier_email, link_type, buy_url, amazon_url, iherb_url, icon_url, image_url, setup_notes, is_active, notes)
VALUES
-- Vitamin D3 - All Regions
('vitamin-d3-5000iu-eu', 'Vitamin D3 5000 IU', 'vitamin_d', 'Vitamin', 'EU', 'EUR', 19.99, 8.50, 57.5, 'Amazon EU', 'https://amazon.de', 'seller-support@amazon.de', 'affiliate', 'https://www.amazon.de/dp/B07QFKV8SY', 'https://www.amazon.de/dp/B07QFKV8SY', 'https://www.iherb.com/pr/now-foods-vitamin-d-3-5000-iu-240-softgels/736', 'https://logo.clearbit.com/amazon.de', 'https://images.unsplash.com/photo-1550572017-4a6e8e0b0d8e?w=400&h=300&fit=crop', '✅ Setup Complete: Amazon affiliate link active, iHerb backup. Take 1 softgel daily with food.', true, 'Supplier: Amazon | Link Type: Affiliate | Commission: 4% | Setup: Confirmed'),
('vitamin-d3-5000iu-uk', 'Vitamin D3 5000 IU', 'vitamin_d', 'Vitamin', 'UK', 'GBP', 16.99, 7.20, 57.6, 'Amazon UK', 'https://amazon.co.uk', 'seller-support@amazon.co.uk', 'affiliate', 'https://www.amazon.co.uk/dp/B07QFKV8SY', 'https://www.amazon.co.uk/dp/B07QFKV8SY', 'https://www.iherb.com/pr/now-foods-vitamin-d-3-5000-iu-240-softgels/736', 'https://logo.clearbit.com/amazon.co.uk', 'https://images.unsplash.com/photo-1550572017-4a6e8e0b0d8e?w=400&h=300&fit=crop', '✅ Setup Complete: Amazon affiliate link active, iHerb backup. Take 1 softgel daily with food.', true, 'Supplier: Amazon | Link Type: Affiliate | Commission: 4% | Setup: Confirmed'),
('vitamin-d3-5000iu-us', 'Vitamin D3 5000 IU', 'vitamin_d', 'Vitamin', 'US', 'USD', 21.99, 9.50, 56.8, 'Amazon US', 'https://amazon.com', 'seller-support@amazon.com', 'affiliate', 'https://www.amazon.com/dp/B07QFKV8SY', 'https://www.amazon.com/dp/B07QFKV8SY', 'https://www.iherb.com/pr/now-foods-vitamin-d-3-5000-iu-240-softgels/736', 'https://logo.clearbit.com/amazon.com', 'https://images.unsplash.com/photo-1550572017-4a6e8e0b0d8e?w=400&h=300&fit=crop', '✅ Setup Complete: Amazon affiliate link active, iHerb backup. Take 1 softgel daily with food.', true, 'Supplier: Amazon | Link Type: Affiliate | Commission: 4% | Setup: Confirmed'),
('vitamin-d3-5000iu-au', 'Vitamin D3 5000 IU', 'vitamin_d', 'Vitamin', 'AU', 'AUD', 29.99, 12.80, 57.3, 'iHerb', 'https://iherb.com', 'support@iherb.com', 'affiliate', 'https://www.iherb.com/pr/now-foods-vitamin-d-3-5000-iu-240-softgels/736', 'https://www.amazon.com.au/dp/B07QFKV8SY', 'https://www.iherb.com/pr/now-foods-vitamin-d-3-5000-iu-240-softgels/736', 'https://logo.clearbit.com/iherb.com', 'https://images.unsplash.com/photo-1550572017-4a6e8e0b0d8e?w=400&h=300&fit=crop', '✅ Setup Complete: iHerb primary link, Amazon backup. Take 1 softgel daily with food.', true, 'Supplier: iHerb | Link Type: Affiliate | Commission: 5% | Setup: Confirmed'),

-- Omega-3 Fish Oil - All Regions
('omega-3-fish-oil-eu', 'Omega-3 Fish Oil 1000mg', 'omega_3', 'Omega', 'EU', 'EUR', 24.99, 11.20, 55.2, 'Amazon EU', 'https://amazon.de', 'seller-support@amazon.de', 'affiliate', 'https://www.amazon.de/dp/B00DQWQVZ8', 'https://www.amazon.de/dp/B00DQWQVZ8', 'https://www.iherb.com/pr/now-foods-omega-3-180-epa-120-dha-200-softgels/424', 'https://logo.clearbit.com/amazon.de', 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=300&fit=crop', '✅ Setup Complete: 180 EPA / 120 DHA per softgel. Take 2 daily with meals. Keep refrigerated.', true, 'Supplier: Amazon | Link Type: Affiliate | Commission: 4% | Setup: Confirmed'),
('omega-3-fish-oil-uk', 'Omega-3 Fish Oil 1000mg', 'omega_3', 'Omega', 'UK', 'GBP', 21.99, 9.80, 55.4, 'Amazon UK', 'https://amazon.co.uk', 'seller-support@amazon.co.uk', 'affiliate', 'https://www.amazon.co.uk/dp/B00DQWQVZ8', 'https://www.amazon.co.uk/dp/B00DQWQVZ8', 'https://www.iherb.com/pr/now-foods-omega-3-180-epa-120-dha-200-softgels/424', 'https://logo.clearbit.com/amazon.co.uk', 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=300&fit=crop', '✅ Setup Complete: 180 EPA / 120 DHA per softgel. Take 2 daily with meals. Keep refrigerated.', true, 'Supplier: Amazon | Link Type: Affiliate | Commission: 4% | Setup: Confirmed'),
('omega-3-fish-oil-us', 'Omega-3 Fish Oil 1000mg', 'omega_3', 'Omega', 'US', 'USD', 27.99, 12.50, 55.3, 'Amazon US', 'https://amazon.com', 'seller-support@amazon.com', 'affiliate', 'https://www.amazon.com/dp/B00DQWQVZ8', 'https://www.amazon.com/dp/B00DQWQVZ8', 'https://www.iherb.com/pr/now-foods-omega-3-180-epa-120-dha-200-softgels/424', 'https://logo.clearbit.com/amazon.com', 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=300&fit=crop', '✅ Setup Complete: 180 EPA / 120 DHA per softgel. Take 2 daily with meals. Keep refrigerated.', true, 'Supplier: Amazon | Link Type: Affiliate | Commission: 4% | Setup: Confirmed'),
('omega-3-fish-oil-au', 'Omega-3 Fish Oil 1000mg', 'omega_3', 'Omega', 'AU', 'AUD', 36.99, 16.50, 55.4, 'iHerb', 'https://iherb.com', 'support@iherb.com', 'affiliate', 'https://www.iherb.com/pr/now-foods-omega-3-180-epa-120-dha-200-softgels/424', 'https://www.amazon.com.au/dp/B00DQWQVZ8', 'https://www.iherb.com/pr/now-foods-omega-3-180-epa-120-dha-200-softgels/424', 'https://logo.clearbit.com/iherb.com', 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=300&fit=crop', '✅ Setup Complete: 180 EPA / 120 DHA per softgel. Take 2 daily with meals. Keep refrigerated.', true, 'Supplier: iHerb | Link Type: Affiliate | Commission: 5% | Setup: Confirmed'),

-- Magnesium Citrate
('magnesium-citrate-400mg-us', 'Magnesium Citrate 400mg', 'magnesium', 'Mineral', 'US', 'USD', 18.99, 8.10, 57.3, 'Amazon US', 'https://amazon.com', 'seller-support@amazon.com', 'affiliate', 'https://www.amazon.com/dp/B00EEZVJY8', 'https://www.amazon.com/dp/B00EEZVJY8', 'https://www.iherb.com/pr/now-foods-magnesium-citrate-200-mg-250-tablets/736', 'https://logo.clearbit.com/amazon.com', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=400&h=300&fit=crop', '✅ Setup Complete: Highly bioavailable citrate form. Take 1-2 tablets daily, best in evening for sleep support.', true, 'Supplier: Amazon | Link Type: Affiliate | Commission: 4% | Setup: Confirmed'),

-- Zinc Picolinate
('zinc-picolinate-50mg-us', 'Zinc Picolinate 50mg', 'zinc', 'Mineral', 'US', 'USD', 16.99, 7.20, 57.6, 'Amazon US', 'https://amazon.com', 'seller-support@amazon.com', 'affiliate', 'https://www.amazon.com/dp/B001G7QG2M', 'https://www.amazon.com/dp/B001G7QG2M', 'https://www.iherb.com/pr/now-foods-zinc-picolinate-50-mg-120-veg-capsules/739', 'https://logo.clearbit.com/amazon.com', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop', '✅ Setup Complete: Highly absorbable picolinate form. Take 1 capsule daily with food. Supports immune function.', true, 'Supplier: Amazon | Link Type: Affiliate | Commission: 4% | Setup: Confirmed'),

-- Dr. Ardis Labs - Nicotine Detox
('ardis-nicotine-detox-us', 'Dr. Ardis Nicotine Detox', 'nicotine', 'Herb', 'US', 'USD', 49.99, 22.50, 55.0, 'Ardis Labs', 'https://thedrardisshow.com', 'support@ardislabs.com', 'direct', 'https://thedrardisshow.com/supplements/', NULL, NULL, 'https://logo.clearbit.com/thedrardisshow.com', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop', '⚠️ Direct Purchase: No affiliate program currently. Contact Ardis Labs for wholesale/dropship options.', true, 'Supplier: Ardis Labs | Link Type: Direct | Dr. Bryan Ardis exclusive formula | Setup: Contact needed for affiliate'),

-- Dr. Wallach Youngevity - 90 For Life Pack
('youngevity-90-for-life-us', 'Youngevity 90 For Life Pack', 'multi_mineral', 'Mineral', 'US', 'USD', 89.99, 45.00, 50.0, 'Youngevity', 'https://youngevity.com', 'support@youngevity.com', 'affiliate', 'https://youngofficial.com/', NULL, NULL, 'https://logo.clearbit.com/youngevity.com', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=400&h=300&fit=crop', '✅ Affiliate Available: Youngevity has MLM/affiliate program. Dr. Joel Wallach 90 essential nutrients formula.', true, 'Supplier: Youngevity | Link Type: Affiliate/MLM | Dr. Joel Wallach formula | Commission: ~30% | Setup: Join Youngevity affiliate program')
ON CONFLICT (slug) DO NOTHING;
