-- ============================================================
-- Seed: catalog_symptoms — 30 common deficiency/excess symptoms
-- Linked to elements by name (element_id can be filled later)
-- Date: 2026-02-26
-- ============================================================

INSERT INTO catalog_symptoms (name, slug, category, body_system, severity, onset_type, description, description_simple, linked_elements_deficiency, linked_elements_excess, common_causes, related_symptoms, reversible, population_risk, icon_name, tags, health_score_impact) VALUES

-- VITAMIN A
('Night Blindness', 'night-blindness', 'visual', 'eyes', 'moderate', 'gradual',
 'Reduced ability to see in low-light conditions caused by insufficient rhodopsin production in the retina.',
 'Difficulty seeing in dim light or at night.',
 '[{"element_name": "Vitamin A", "strength": "strong"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['retinitis pigmentosa', 'cataracts', 'zinc deficiency'],
 ARRAY['Dry Eyes', 'Frequent Infections'],
 true, ARRAY['children', 'pregnant'], 'Eye', ARRAY['vision', 'retina'], 15),

('Dry Skin (Xerosis)', 'dry-skin-xerosis', 'dermatological', 'skin', 'mild', 'gradual',
 'Rough, flaky, or scaly skin caused by impaired epithelial cell turnover from insufficient vitamin A.',
 'Skin becomes dry, rough, and flaky.',
 '[{"element_name": "Vitamin A", "strength": "strong"}, {"element_name": "Omega-3", "strength": "moderate"}, {"element_name": "Vitamin E", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['dehydration', 'hypothyroidism', 'eczema', 'harsh soaps'],
 ARRAY['Brittle Nails', 'Dry Hair'],
 true, ARRAY['elderly', 'children'], 'Droplets', ARRAY['skin', 'epithelial'], 8),

-- VITAMIN D
('Bone Pain', 'bone-pain', 'skeletal', 'bones', 'moderate', 'gradual',
 'Aching or tenderness in bones, often in the lower back, hips, and legs, due to impaired calcium absorption from vitamin D deficiency.',
 'Aching bones, especially in the back, hips and legs.',
 '[{"element_name": "Vitamin D", "strength": "strong"}, {"element_name": "Calcium", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['osteoporosis', 'arthritis', 'injury', 'overuse'],
 ARRAY['Muscle Weakness', 'Fatigue'],
 true, ARRAY['elderly', 'indoor workers', 'dark skin'], 'Bone', ARRAY['bones', 'skeletal'], 18),

('Frequent Infections', 'frequent-infections', 'immune', 'immune', 'moderate', 'gradual',
 'Recurring colds, flu, and respiratory infections due to compromised immune function from vitamin D deficiency.',
 'Getting sick more often than normal.',
 '[{"element_name": "Vitamin D", "strength": "strong"}, {"element_name": "Vitamin C", "strength": "strong"}, {"element_name": "Zinc", "strength": "strong"}, {"element_name": "Vitamin A", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['stress', 'poor sleep', 'chronic illness', 'HIV'],
 ARRAY['Fatigue', 'Slow Wound Healing'],
 true, ARRAY['elderly', 'children', 'immunocompromised'], 'ShieldAlert', ARRAY['immune', 'infection'], 20),

('Muscle Weakness', 'muscle-weakness', 'muscular', 'muscles', 'moderate', 'gradual',
 'Reduced muscle strength and difficulty with physical tasks, linked to vitamin D''s role in muscle fiber function.',
 'Feeling weaker than usual, difficulty lifting or climbing stairs.',
 '[{"element_name": "Vitamin D", "strength": "strong"}, {"element_name": "Magnesium", "strength": "moderate"}, {"element_name": "Potassium", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['sedentary lifestyle', 'aging', 'neurological conditions'],
 ARRAY['Fatigue', 'Bone Pain', 'Muscle Cramps'],
 true, ARRAY['elderly', 'sedentary'], 'Dumbbell', ARRAY['muscle', 'strength'], 15),

-- IRON
('Fatigue', 'fatigue', 'general', 'whole body', 'moderate', 'gradual',
 'Persistent tiredness and lack of energy caused by insufficient oxygen delivery to tissues due to low iron/hemoglobin.',
 'Feeling tired all the time, even after sleeping.',
 '[{"element_name": "Iron", "strength": "strong"}, {"element_name": "Vitamin B12", "strength": "strong"}, {"element_name": "Vitamin D", "strength": "moderate"}, {"element_name": "Folate", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['poor sleep', 'depression', 'hypothyroidism', 'chronic fatigue syndrome'],
 ARRAY['Pale Skin', 'Shortness of Breath', 'Dizziness'],
 true, ARRAY['women', 'pregnant', 'vegans'], 'Battery', ARRAY['energy', 'anemia'], 22),

('Pale Skin', 'pale-skin', 'dermatological', 'skin', 'mild', 'gradual',
 'Unusually light or washed-out skin color due to reduced hemoglobin in blood from iron deficiency anemia.',
 'Skin looks paler than usual, especially inner eyelids and nailbeds.',
 '[{"element_name": "Iron", "strength": "strong"}, {"element_name": "Vitamin B12", "strength": "moderate"}, {"element_name": "Folate", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['blood loss', 'chronic disease', 'genetic anemia'],
 ARRAY['Fatigue', 'Shortness of Breath'],
 true, ARRAY['women', 'pregnant', 'vegans'], 'User', ARRAY['skin', 'anemia'], 12),

('Brittle Nails', 'brittle-nails', 'dermatological', 'nails', 'mild', 'gradual',
 'Nails that are thin, crack easily, or develop spoon-shaped concavity (koilonychia) due to iron deficiency.',
 'Nails break or chip easily and may look spoon-shaped.',
 '[{"element_name": "Iron", "strength": "strong"}, {"element_name": "Biotin", "strength": "moderate"}, {"element_name": "Zinc", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['frequent hand washing', 'nail polish use', 'hypothyroidism'],
 ARRAY['Dry Skin (Xerosis)', 'Hair Loss'],
 true, ARRAY['women'], 'Hand', ARRAY['nails', 'iron'], 6),

-- VITAMIN C
('Bleeding Gums', 'bleeding-gums', 'oral', 'mouth', 'moderate', 'gradual',
 'Gums that bleed easily when brushing or eating due to weakened blood vessels and collagen from vitamin C deficiency.',
 'Gums bleed when you brush teeth or eat hard food.',
 '[{"element_name": "Vitamin C", "strength": "strong"}, {"element_name": "Vitamin K", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['gingivitis', 'periodontitis', 'blood thinners'],
 ARRAY['Slow Wound Healing', 'Easy Bruising'],
 true, ARRAY['smokers', 'elderly'], 'Smile', ARRAY['gums', 'scurvy'], 14),

('Slow Wound Healing', 'slow-wound-healing', 'immune', 'skin', 'moderate', 'gradual',
 'Cuts, scrapes, and injuries take longer to heal due to impaired collagen synthesis from vitamin C deficiency.',
 'Cuts and wounds take much longer to heal than normal.',
 '[{"element_name": "Vitamin C", "strength": "strong"}, {"element_name": "Zinc", "strength": "strong"}, {"element_name": "Vitamin A", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['diabetes', 'poor circulation', 'immunosuppression'],
 ARRAY['Bleeding Gums', 'Easy Bruising', 'Frequent Infections'],
 true, ARRAY['smokers', 'elderly', 'diabetics'], 'Bandage', ARRAY['healing', 'collagen'], 16),

('Easy Bruising', 'easy-bruising', 'dermatological', 'skin', 'mild', 'gradual',
 'Bruises appearing with minimal impact due to fragile capillaries from insufficient vitamin C or K.',
 'Getting bruises easily, even from small bumps.',
 '[{"element_name": "Vitamin C", "strength": "strong"}, {"element_name": "Vitamin K", "strength": "strong"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['blood thinners', 'aging', 'liver disease'],
 ARRAY['Bleeding Gums', 'Slow Wound Healing'],
 true, ARRAY['elderly', 'women'], 'CircleDot', ARRAY['bruising', 'capillaries'], 10),

-- VITAMIN B12
('Numbness and Tingling', 'numbness-tingling', 'neurological', 'nervous system', 'moderate', 'gradual',
 'Pins and needles sensation in hands and feet caused by nerve damage from B12 deficiency demyelination.',
 'Tingling or numbness in your hands and feet.',
 '[{"element_name": "Vitamin B12", "strength": "strong"}, {"element_name": "Vitamin B6", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['diabetes neuropathy', 'carpal tunnel', 'multiple sclerosis'],
 ARRAY['Fatigue', 'Memory Problems', 'Balance Issues'],
 true, ARRAY['vegans', 'elderly', 'pernicious anemia'], 'Zap', ARRAY['nerves', 'neuropathy'], 20),

('Memory Problems', 'memory-problems', 'neurological', 'brain', 'moderate', 'gradual',
 'Difficulty concentrating, brain fog, and memory lapses due to impaired myelin production from B12 deficiency.',
 'Trouble remembering things or focusing on tasks.',
 '[{"element_name": "Vitamin B12", "strength": "strong"}, {"element_name": "Iron", "strength": "moderate"}, {"element_name": "Omega-3", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['stress', 'poor sleep', 'aging', 'depression'],
 ARRAY['Fatigue', 'Numbness and Tingling'],
 true, ARRAY['vegans', 'elderly'], 'Brain', ARRAY['cognitive', 'memory'], 18),

-- MAGNESIUM
('Muscle Cramps', 'muscle-cramps', 'muscular', 'muscles', 'moderate', 'acute',
 'Involuntary, painful muscle contractions especially at night, caused by magnesium''s role in muscle relaxation.',
 'Sudden, painful cramps especially in legs at night.',
 '[{"element_name": "Magnesium", "strength": "strong"}, {"element_name": "Potassium", "strength": "moderate"}, {"element_name": "Calcium", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['dehydration', 'overexercise', 'pregnancy', 'diuretics'],
 ARRAY['Muscle Weakness', 'Insomnia', 'Heart Palpitations'],
 true, ARRAY['athletes', 'pregnant', 'elderly'], 'Activity', ARRAY['muscle', 'cramps', 'electrolyte'], 14),

('Insomnia', 'insomnia', 'psychological', 'brain', 'moderate', 'gradual',
 'Difficulty falling or staying asleep due to magnesium''s role in GABA regulation and nervous system relaxation.',
 'Trouble falling asleep or waking up frequently at night.',
 '[{"element_name": "Magnesium", "strength": "strong"}, {"element_name": "Vitamin D", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['stress', 'anxiety', 'caffeine', 'screen time', 'sleep apnea'],
 ARRAY['Fatigue', 'Anxiety', 'Muscle Cramps'],
 true, ARRAY['stressed individuals', 'elderly'], 'Moon', ARRAY['sleep', 'GABA'], 16),

('Heart Palpitations', 'heart-palpitations', 'cardiovascular', 'heart', 'severe', 'acute',
 'Irregular or racing heartbeat due to electrolyte imbalance affecting cardiac muscle electrical activity.',
 'Heart feels like it''s racing, fluttering, or skipping beats.',
 '[{"element_name": "Magnesium", "strength": "strong"}, {"element_name": "Potassium", "strength": "strong"}, {"element_name": "Calcium", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['caffeine', 'anxiety', 'arrhythmia', 'thyroid disease'],
 ARRAY['Anxiety', 'Muscle Cramps', 'Fatigue'],
 true, ARRAY['athletes', 'elderly', 'caffeinated'], 'HeartPulse', ARRAY['heart', 'arrhythmia', 'electrolyte'], 25),

-- ZINC
('Hair Loss', 'hair-loss', 'dermatological', 'hair', 'moderate', 'gradual',
 'Increased hair shedding and thinning due to zinc''s role in hair follicle protein synthesis and cell division.',
 'More hair falling out than usual, thinning patches.',
 '[{"element_name": "Zinc", "strength": "strong"}, {"element_name": "Iron", "strength": "strong"}, {"element_name": "Biotin", "strength": "moderate"}, {"element_name": "Vitamin D", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['genetics', 'hormonal changes', 'stress', 'thyroid disease'],
 ARRAY['Brittle Nails', 'Dry Skin (Xerosis)'],
 true, ARRAY['women', 'postpartum', 'vegans'], 'Scissors', ARRAY['hair', 'alopecia'], 14),

('Loss of Taste/Smell', 'loss-taste-smell', 'neurological', 'mouth', 'mild', 'gradual',
 'Reduced ability to taste or smell food due to zinc''s role in gustatory and olfactory receptor renewal.',
 'Food tastes bland or you can''t smell things as well.',
 '[{"element_name": "Zinc", "strength": "strong"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['aging', 'viral infections', 'medications', 'nasal polyps'],
 ARRAY['Poor Appetite', 'Frequent Infections'],
 true, ARRAY['elderly', 'vegans'], 'UtensilsCrossed', ARRAY['taste', 'smell', 'anosmia'], 10),

-- CALCIUM
('Osteoporosis Risk', 'osteoporosis-risk', 'skeletal', 'bones', 'severe', 'chronic',
 'Progressive bone density loss increasing fracture risk, from chronic calcium deficiency impairing bone mineralization.',
 'Bones become fragile and break more easily.',
 '[{"element_name": "Calcium", "strength": "strong"}, {"element_name": "Vitamin D", "strength": "strong"}, {"element_name": "Vitamin K", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['menopause', 'aging', 'sedentary lifestyle', 'corticosteroids'],
 ARRAY['Bone Pain', 'Muscle Cramps'],
 false, ARRAY['postmenopausal women', 'elderly', 'thin build'], 'Bone', ARRAY['osteoporosis', 'fracture'], 28),

('Tooth Decay', 'tooth-decay', 'oral', 'mouth', 'moderate', 'chronic',
 'Weakening of tooth enamel and increased cavities due to insufficient calcium and phosphorus for tooth mineralization.',
 'Teeth becoming weak, more cavities than usual.',
 '[{"element_name": "Calcium", "strength": "strong"}, {"element_name": "Vitamin D", "strength": "moderate"}, {"element_name": "Phosphorus", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['poor dental hygiene', 'sugar intake', 'dry mouth'],
 ARRAY['Osteoporosis Risk', 'Bone Pain'],
 false, ARRAY['children', 'elderly'], 'Smile', ARRAY['teeth', 'enamel'], 12),

-- POTASSIUM
('High Blood Pressure', 'high-blood-pressure', 'cardiovascular', 'heart', 'severe', 'chronic',
 'Elevated blood pressure due to sodium-potassium imbalance affecting vascular smooth muscle tone and fluid regulation.',
 'Blood pressure readings consistently above normal.',
 '[{"element_name": "Potassium", "strength": "strong"}, {"element_name": "Magnesium", "strength": "moderate"}]'::jsonb,
 '[{"element_name": "Sodium", "strength": "strong"}]'::jsonb,
 ARRAY['genetics', 'obesity', 'stress', 'high sodium diet', 'kidney disease'],
 ARRAY['Heart Palpitations', 'Headaches'],
 true, ARRAY['elderly', 'obese', 'high sodium diet'], 'Activity', ARRAY['hypertension', 'cardiovascular'], 30),

-- IODINE
('Goiter', 'goiter', 'hormonal', 'endocrine', 'severe', 'chronic',
 'Enlargement of the thyroid gland in the neck due to iodine deficiency impairing thyroid hormone production.',
 'Swelling in the front of the neck (enlarged thyroid).',
 '[{"element_name": "Iodine", "strength": "strong"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['Graves disease', 'Hashimoto thyroiditis', 'thyroid nodules'],
 ARRAY['Fatigue', 'Weight Changes'],
 true, ARRAY['inland populations', 'vegans'], 'CircleDot', ARRAY['thyroid', 'goiter'], 22),

('Weight Changes', 'weight-changes', 'hormonal', 'endocrine', 'moderate', 'gradual',
 'Unexplained weight gain (hypothyroidism) or loss (hyperthyroidism) from thyroid dysfunction related to iodine.',
 'Gaining or losing weight without changing diet or exercise.',
 '[{"element_name": "Iodine", "strength": "strong"}]'::jsonb,
 '[{"element_name": "Iodine", "strength": "moderate"}]'::jsonb,
 ARRAY['thyroid disease', 'diabetes', 'medications', 'stress'],
 ARRAY['Fatigue', 'Goiter'],
 true, ARRAY['women', 'middle-aged'], 'Scale', ARRAY['weight', 'thyroid', 'metabolism'], 16),

-- FOLATE
('Neural Tube Defects Risk', 'neural-tube-defects', 'developmental', 'nervous system', 'severe', 'acute',
 'Increased risk of spina bifida and anencephaly in developing fetus due to folate deficiency during early pregnancy.',
 'Birth defect risk: baby''s spine or brain may not develop properly.',
 '[{"element_name": "Folate", "strength": "strong"}, {"element_name": "Vitamin B12", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['genetics', 'anti-epileptic drugs', 'diabetes'],
 ARRAY['Fatigue', 'Pale Skin'],
 false, ARRAY['pregnant', 'women of childbearing age'], 'Baby', ARRAY['pregnancy', 'neural tube', 'birth defect'], 35),

('Mouth Ulcers', 'mouth-ulcers', 'oral', 'mouth', 'mild', 'acute',
 'Painful sores inside the mouth or on the tongue from impaired cell turnover due to folate or B12 deficiency.',
 'Painful sores inside the mouth that keep coming back.',
 '[{"element_name": "Folate", "strength": "strong"}, {"element_name": "Vitamin B12", "strength": "strong"}, {"element_name": "Iron", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['stress', 'food sensitivities', 'Crohn disease', 'celiac disease'],
 ARRAY['Fatigue', 'Pale Skin'],
 true, ARRAY['vegans', 'celiac patients'], 'Smile', ARRAY['mouth', 'ulcer', 'aphthous'], 8),

-- EXCESS SYMPTOMS

-- VITAMIN A EXCESS
('Liver Damage (Hypervitaminosis A)', 'liver-damage-vitamin-a', 'hepatic', 'liver', 'severe', 'chronic',
 'Hepatotoxicity from chronic excess vitamin A (retinol) accumulation overwhelming liver storage capacity.',
 'Liver damage from taking too much vitamin A over time.',
 '[]'::jsonb,
 '[{"element_name": "Vitamin A", "strength": "strong"}]'::jsonb,
 ARRAY['alcohol abuse', 'hepatitis', 'medications'],
 ARRAY['Nausea', 'Jaundice', 'Hair Loss'],
 false, ARRAY['supplement users', 'liver disease'], 'AlertTriangle', ARRAY['liver', 'toxicity', 'hypervitaminosis'], 30),

('Nausea', 'nausea', 'digestive', 'gut', 'mild', 'acute',
 'Feeling of sickness and urge to vomit, commonly caused by excess intake of fat-soluble vitamins or iron.',
 'Feeling sick to your stomach.',
 '[{"element_name": "Iron", "strength": "moderate"}]'::jsonb,
 '[{"element_name": "Vitamin A", "strength": "strong"}, {"element_name": "Iron", "strength": "strong"}, {"element_name": "Vitamin D", "strength": "moderate"}, {"element_name": "Zinc", "strength": "moderate"}]'::jsonb,
 ARRAY['pregnancy', 'food poisoning', 'medications', 'motion sickness'],
 ARRAY['Headaches', 'Dizziness'],
 true, ARRAY['supplement users', 'pregnant'], 'AlertCircle', ARRAY['digestive', 'nausea'], 8),

-- IRON EXCESS
('Iron Overload (Hemochromatosis)', 'iron-overload', 'hepatic', 'liver', 'severe', 'chronic',
 'Excess iron depositing in organs (liver, heart, pancreas) causing oxidative damage and organ failure.',
 'Too much iron stored in body causing damage to organs.',
 '[]'::jsonb,
 '[{"element_name": "Iron", "strength": "strong"}]'::jsonb,
 ARRAY['hereditary hemochromatosis', 'repeated transfusions'],
 ARRAY['Fatigue', 'Joint Pain', 'Liver Damage (Hypervitaminosis A)'],
 false, ARRAY['men', 'postmenopausal women', 'genetic carriers'], 'AlertTriangle', ARRAY['iron', 'hemochromatosis', 'overload'], 32),

-- SODIUM EXCESS
('Edema (Swelling)', 'edema-swelling', 'cardiovascular', 'whole body', 'moderate', 'acute',
 'Fluid retention and swelling in extremities from excess sodium causing the body to retain water.',
 'Puffy ankles, hands, or face from water retention.',
 '[{"element_name": "Vitamin B6", "strength": "mild"}]'::jsonb,
 '[{"element_name": "Sodium", "strength": "strong"}]'::jsonb,
 ARRAY['heart failure', 'kidney disease', 'liver disease', 'medications'],
 ARRAY['High Blood Pressure', 'Weight Changes'],
 true, ARRAY['high sodium diet', 'elderly', 'heart disease'], 'Droplets', ARRAY['edema', 'swelling', 'fluid retention'], 18),

-- GENERAL CROSSOVER
('Headaches', 'headaches', 'neurological', 'brain', 'mild', 'acute',
 'Recurring headaches from various nutrient imbalances affecting blood vessel dilation and nervous system function.',
 'Frequent headaches that may be related to nutrient levels.',
 '[{"element_name": "Magnesium", "strength": "strong"}, {"element_name": "Iron", "strength": "moderate"}, {"element_name": "Vitamin B2", "strength": "moderate"}]'::jsonb,
 '[{"element_name": "Vitamin A", "strength": "moderate"}, {"element_name": "Vitamin D", "strength": "moderate"}]'::jsonb,
 ARRAY['stress', 'dehydration', 'tension', 'migraine', 'high blood pressure'],
 ARRAY['Nausea', 'Dizziness', 'Fatigue'],
 true, ARRAY['women', 'stressed individuals'], 'Brain', ARRAY['headache', 'migraine'], 10),

('Dizziness', 'dizziness', 'neurological', 'brain', 'moderate', 'acute',
 'Lightheadedness or vertigo from reduced oxygen delivery (anemia) or electrolyte/blood pressure imbalances.',
 'Feeling lightheaded or like the room is spinning.',
 '[{"element_name": "Iron", "strength": "strong"}, {"element_name": "Vitamin B12", "strength": "moderate"}, {"element_name": "Potassium", "strength": "moderate"}]'::jsonb,
 '[]'::jsonb,
 ARRAY['dehydration', 'low blood pressure', 'inner ear problems', 'anxiety'],
 ARRAY['Fatigue', 'Pale Skin', 'Heart Palpitations'],
 true, ARRAY['elderly', 'anemic patients'], 'RotateCcw', ARRAY['vertigo', 'lightheaded'], 14),

('Anxiety', 'anxiety', 'psychological', 'brain', 'moderate', 'gradual',
 'Excessive worry and nervousness linked to magnesium deficiency (impaired GABA) and B-vitamin deficiency.',
 'Feeling worried, nervous, or on edge more than usual.',
 '[{"element_name": "Magnesium", "strength": "strong"}, {"element_name": "Vitamin B6", "strength": "moderate"}, {"element_name": "Vitamin D", "strength": "moderate"}, {"element_name": "Omega-3", "strength": "moderate"}]'::jsonb,
 '[{"element_name": "Caffeine", "strength": "strong"}]'::jsonb,
 ARRAY['stress', 'genetics', 'trauma', 'thyroid disease'],
 ARRAY['Insomnia', 'Heart Palpitations', 'Muscle Cramps'],
 true, ARRAY['women', 'stressed individuals'], 'AlertCircle', ARRAY['anxiety', 'mental health', 'GABA'], 18);
