-- Seed Part 2: Combination, Smoke & Fire, Dehydration, Fermentation, Raw/Acid, Modern
-- Run AFTER Part 1
-- NOTE: equipment_needed column was dropped; equipment_ids (uuid[]) populated separately via linking script

INSERT INTO catalog_cooking_methods (name, slug, category, description, temperature, medium, typical_time, health_impact, nutrient_effect, best_for) VALUES

-- COMBINATION / MIXED
('Braising','braising','Combination','Searing food in fat then slowly cooking covered in small amount of liquid.','Low-Med (150–175°C)','Fat then liquid','1–4 hrs','Combines browning and slow moist cooking; collagen melts.','Minerals retained; some vitamin loss over time.','Short ribs, lamb shanks, pork shoulder, cabbage'),
('Pot Roasting','pot-roasting','Combination','Searing large cut then braising covered with vegetables and liquid.','Low-Med (150–175°C)','Fat then liquid','2–4 hrs','One-pot meal retains nutrients in sauce.','Good — consumed with cooking liquid.','Beef chuck, pork loin, whole chicken'),
('En Papillote','en-papillote','Combination','Wrapping food in parchment and baking to steam in own juices. French origin.','Medium (180–200°C)','Own juices (steam)','15–25 min','Very healthy; no added fat needed.','Excellent — juices sealed in.','Fish, chicken, vegetables, herbs'),
('Casserole','casserole','Combination','Layered dish baked slowly in oven-safe vessel.','Medium (160–190°C)','Liquid + oven heat','30 min–2 hrs','Nutrients stay in dish.','Mixed — depends on duration.','Lasagna, moussaka, shepherd''s pie, gratins'),
('Fricassée','fricassee','Combination','White stew: meat sautéed without browning, simmered in cream sauce. French origin.','Medium (85–96°C)','Butter then cream/stock','30–60 min','Rich; cream adds calories. Gentle cook preserves protein.','Moderate; consumed with sauce.','Chicken, rabbit, veal, mushrooms'),
('Étouffée','etouffee','Combination','Smothering food in roux-based sauce, covered. Cajun/Creole origin.','Medium (85–96°C)','Roux + stock','30–45 min','Rich roux base; flavourful and calorie-dense.','Nutrients retained in sauce.','Crawfish, shrimp, chicken'),
('Cataplana','cataplana','Combination','Portuguese hinged copper pot that seals food to steam-braise simultaneously.','Medium (85–100°C)','Own juices + wine/stock','20–40 min','Sealed environment preserves moisture and nutrients.','Excellent — steam and juices retained.','Seafood, pork and clams, vegetables'),
('Drunken Cooking (Beer/Wine Braising)','drunken-cooking','Combination','Braising or simmering food in beer, wine, or spirits. European origin.','Medium (85–100°C)','Alcohol-based liquid','1–3 hrs','Alcohol cooks off mostly; residual antioxidants from wine.','Minerals retained; polyphenols from wine.','Coq au vin, beer-braised beef, drunken chicken'),
('Porchetta Rolling','porchetta-rolling','Combination','Italian method of deboning, seasoning, rolling, and slow-roasting whole pig or belly.','Med-High (150–200°C)','Dry heat + self-basting fat','3–5 hrs','Fat renders and self-bastes; crispy skin. Very flavourful.','Good mineral retention; fat drips away.','Porchetta (whole pig belly), pork loin'),

-- SMOKE & FIRE
('Hot Smoking','hot-smoking','Smoke & Fire','Exposing food to smoke and heat simultaneously, cooking and flavouring.','Medium (55–135°C)','Wood smoke + heat','1–8 hrs','PAH and nitrosamine exposure; moderate consumption advised.','Protein retained; some B-vitamin loss.','Salmon, ribs, brisket, sausages, cheese'),
('Cold Smoking','cold-smoking','Smoke & Fire','Exposing food to smoke without significant heat; requires prior curing.','Low (<30°C)','Wood smoke only','12–48 hrs','Food remains raw; smoke preserves. Curing salt required.','Minimal heat-related nutrient change.','Salmon, bacon, cheese, ham'),
('Ember Roasting','ember-roasting','Smoke & Fire','Placing food directly on/in hot coals. Ancient worldwide technique.','Very High (variable)','Direct embers/coals','10–45 min','Charring risk; smoky flavour.','Minerals retained; some vitamin destruction.','Eggplant (baba ganoush), peppers, corn, sweet potatoes'),
('Plank Grilling','plank-grilling','Smoke & Fire','Cooking on soaked wooden plank over grill. North American First Nations origin.','Medium (175–200°C)','Wood plank + indirect heat','15–25 min','Gentler than direct grilling; wood flavour infusion.','Good nutrient retention.','Salmon, chicken, vegetables, cheese'),
('Flambéing','flambeing','Smoke & Fire','Igniting alcohol in hot pan for dramatic flame burst. French origin.','Very High (brief)','Alcohol + flame','10–30 sec','Alcohol mostly burns off; brief heat minimal impact.','Negligible nutrient effect.','Crêpes Suzette, steak Diane, bananas Foster'),
('Hay Smoking','hay-smoking','Smoke & Fire','Burning hay around food for delicate grassy smoke. Nordic/European origin.','Low-Medium (variable)','Smouldering hay','5–20 min','Very light smoke exposure.','Negligible.','Cheese, fish, root vegetables'),
('Yakitori (Charcoal Skewer)','yakitori','Smoke & Fire','Japanese skewered chicken grilled over binchotan charcoal.','High (200–300°C)','Binchotan charcoal','5–10 min','Quick sear; minimal HCA if not over-charred.','Good — quick cook preserves nutrients.','Chicken parts (skin, thigh, liver), vegetables'),
('Asado','asado','Smoke & Fire','South American whole-animal grilling over wood/charcoal at varying distances.','Med-High (variable)','Wood/charcoal fire','2–8 hrs','Slow cook; fat renders off. Social tradition.','Good mineral retention.','Beef ribs, whole lamb, chorizo, morcilla'),
('Lechón / Spit Roasting','lechon','Smoke & Fire','Whole pig or lamb roasted on spit over open fire. Filipino/Latin/Mediterranean.','Medium (variable)','Open fire + spit rotation','4–12 hrs','Fat renders away; skin crisps. Collagen breaks down.','Good overall; consumed with juices.','Whole pig, lamb, goat'),
('Imu / Earth Oven','imu-earth-oven','Smoke & Fire','Hawaiian underground oven using hot rocks and banana/ti leaves.','Medium (retained heat)','Hot lava rocks + leaves','8–16 hrs','Slow, sealed underground cook; extremely tender.','Excellent — sealed environment.','Kalua pig, taro, sweet potato, fish'),
('Hangi','hangi','Smoke & Fire','Māori earth oven: food wrapped and buried with hot stones. New Zealand.','Medium (retained heat)','Hot stones + earth insulation','3–6 hrs','Underground steam-roast; very moist. Cultural ceremony.','Good — sealed, moist environment.','Pork, chicken, kumara, pumpkin, cabbage'),
('Pachamanca','pachamanca','Smoke & Fire','Peruvian/Andean underground cooking with hot stones. Pre-Inca origin.','Medium (retained heat)','Hot stones + earth','2–4 hrs','Slow earth-oven; tender results. Ceremonial.','Good retention in sealed pit.','Lamb, pork, potatoes, corn, fava beans, humitas'),
('Cochinita Pibil / Pib','pib-cooking','Smoke & Fire','Yucatecan Mayan cooking in underground pit (pib) with banana leaf wrap.','Medium (retained heat)','Hot coals + banana leaves + earth','6–12 hrs','Underground slow-roast; achiote marinade adds antioxidants.','Good retention; sealed with leaves.','Cochinita pibil (pork), tamales, mukbil pollo'),

-- DEHYDRATION & PRESERVATION
('Dehydrating','dehydrating','Dehydration','Removing moisture using low heat and air circulation.','Low (50–70°C)','Warm air circulation','4–24 hrs','Concentrates nutrients per gram; some vitamin C/A loss.','Minerals concentrated; heat-sensitive vitamins reduced.','Jerky, fruit leather, dried herbs, mushrooms'),
('Freeze-Drying','freeze-drying','Dehydration','Freezing then removing ice by sublimation under vacuum.','Very Low (−40°C then vacuum)','Vacuum sublimation','24–48 hrs','Best nutrient preservation of all drying methods.','Excellent — structure and nutrients intact.','Astronaut food, camping meals, fruit, coffee'),
('Sun Drying','sun-drying','Dehydration','Traditional drying using sunlight and air. Ancient worldwide.','Low (ambient + sun)','Sunlight + air','2–5 days','UV degrades some vitamins; zero-energy method.','Significant vitamin C loss; minerals concentrated.','Tomatoes, raisins, figs, dates, fish, chillies'),
('Curing (Salt/Sugar)','curing','Dehydration','Preserving with salt, sugar, nitrates drawing out moisture.','None (ambient)','Salt / sugar / nitrates','1–30 days','High sodium; nitrate debate. Effective preservation.','Nutrients mostly retained; high sodium.','Bacon, ham, gravlax, salami, corned beef'),
('Vinegar Pickling','pickling-vinegar','Dehydration','Preserving food in acidic vinegar solution.','None or brief boil','Vinegar brine','1–30 days','Vinegar preserves well; retains crunch.','Some vitamin C preserved; acidity aids absorption.','Cucumbers, onions, beets, jalapeños, eggs'),
('Lacto-Fermentation Pickling','lacto-fermentation','Dehydration','Preserving using lactobacillus bacteria in salt brine.','None (ambient)','Salt brine + bacteria','3–30 days','Creates probiotics; reduces anti-nutrients.','Enhanced B-vitamins; probiotics created.','Sauerkraut, kimchi, pickles, curtido, torshi'),
('Biltong / Air Drying','biltong','Dehydration','South African air-drying of spiced, cured meat.','None (ambient, cool, dry)','Air circulation','3–7 days','High protein, low fat. Vinegar wash adds safety.','Minerals concentrated; some vitamin loss.','Beef, game meats (kudu, ostrich)'),
('Buccanning (Smoke-Drying)','buccanning','Dehydration','Slow-smoking meat on wooden frame. Caribbean Taino origin.','Low (indirect smoke)','Wood smoke + air','1–3 days','Smoke preserves; long process.','Protein concentrated; some vitamin loss.','Pork, beef, fish, game'),
('Pemmican Making','pemmican-making','Dehydration','Drying meat, pounding to powder, mixing with fat and berries. Indigenous North American.','Low then none','Air drying + fat binding','2–5 days','Extremely calorie-dense; complete survival food.','Concentrated protein, fat, vitamins from berries.','Bison, elk, deer, beef'),
('Katsuobushi (Bonito Drying)','katsuobushi','Dehydration','Japanese process of smoking, drying, and mould-fermenting bonito fish for months.','Low then ambient','Smoke + air + mould','3–6 months','One of hardest foods; concentrated umami. Rich in inosinic acid.','Highly concentrated protein and minerals.','Dashi stock, okonomiyaki, takoyaki, rice topping'),
('Pastirma / Basturma Making','pastirma','Dehydration','Turkish/Armenian air-dried cured beef coated in fenugreek paste (çemen).','None (ambient)','Salt cure + air + çemen paste','2–3 weeks','High protein; çemen adds antioxidants and antimicrobials.','Concentrated protein and minerals.','Pastirma slices, breakfast, eggs, flatbread'),

-- FERMENTATION
('General Fermentation','fermentation','Fermentation','Microbial conversion of sugars into acids, gases, or alcohol.','Ambient (20–30°C)','Bacteria / yeast cultures','1 day–months','Produces probiotics; increases mineral bioavailability.','Enhanced — probiotics, B12, K2 created.','Yoghurt, kefir, tempeh, miso, sourdough, kombucha'),
('Koji Fermentation','koji-fermentation','Fermentation','Inoculating grains with Aspergillus oryzae mould. Japanese origin.','Warm (28–35°C)','Aspergillus oryzae mould','2–4 days','Produces powerful umami; enzymes break down proteins.','Enhanced amino acids; glutamate created.','Soy sauce, miso, sake, amazake, shio koji'),
('Natto Fermentation','natto-fermentation','Fermentation','Soybeans fermented with Bacillus subtilis. Japanese origin.','Warm (40–45°C)','Bacillus subtilis bacteria','22–24 hrs','Rich in nattokinase and vitamin K2.','Exceptional K2 and protein bioavailability.','Natto (with rice, in sushi)'),
('Dosa / Idli Fermentation','dosa-fermentation','Fermentation','Rice and lentil batter fermentation. South Indian origin.','Warm ambient (28–35°C)','Wild yeast + lactobacilli','8–24 hrs','Fermentation increases B-vitamins and mineral bioavailability.','Enhanced iron and B-vitamin absorption.','Dosa, idli, uttapam'),
('Tepache Fermentation','tepache-fermentation','Fermentation','Mexican fermented pineapple drink with piloncillo and spices.','Ambient (20–30°C)','Wild yeast fermentation','2–5 days','Low alcohol; probiotic. Bromelain partially survives.','Probiotics created; some vitamin C retained.','Tepache beverage'),
('Injera Fermentation','injera-fermentation','Fermentation','Ethiopian teff batter fermented for spongy sour flatbread.','Ambient (20–30°C)','Wild yeast + lactobacilli','1–3 days','Fermentation increases iron bioavailability of teff.','Enhanced mineral absorption; B-vitamins created.','Injera (Ethiopian/Eritrean flatbread)'),
('Chicha Fermentation','chicha-fermentation','Fermentation','Andean fermented corn beer, traditionally using saliva amylase to start fermentation.','Ambient','Wild yeast + amylase','3–7 days','Low alcohol; probiotic. Traditional ceremonial drink.','B-vitamins created through fermentation.','Chicha (corn beer)'),
('Ogi / Akamu Fermentation','ogi-fermentation','Fermentation','West African fermented cereal pudding from maize, sorghum, or millet.','Ambient (25–35°C)','Lactobacillus + yeast','2–3 days','Reduces anti-nutrients (phytates); probiotics created.','Enhanced iron and zinc bioavailability.','Ogi/akamu (porridge), pap'),
('Kvass Fermentation','kvass-fermentation','Fermentation','Eastern European fermented bread drink. Russian/Ukrainian origin.','Ambient','Yeast + lactobacilli','1–3 days','Low alcohol (<1%); probiotic. Good source of B-vitamins.','B-vitamins from bread + fermentation.','Kvass beverage'),

-- RAW & ACID-BASED
('Ceviche','ceviche','Raw / Acid','Denaturing protein using citrus acid. Latin American origin.','None (acid)','Citrus juice (lime, lemon)','15–60 min','Acid cooks protein surface; use sushi-grade fish.','Maximum vitamin and enzyme retention.','Fish, shrimp, scallops, octopus'),
('Tartare / Raw Preparation','tartare-raw','Raw / Acid','Serving food completely raw, finely chopped or sliced.','None','None','N/A','Maximum nutrient retention; food safety risk with proteins.','All nutrients intact; enzymes active.','Beef tartare, sashimi, carpaccio, salads'),
('Kinilaw','kinilaw','Raw / Acid','Filipino ceviche using vinegar (not citrus) for raw seafood.','None (acid)','Vinegar (coconut/cane)','15–30 min','Vinegar denatures protein; different from citrus ceviche.','Maximum retention; enzymes mostly active.','Fish, shrimp, sea urchin, squid'),
('Sashimi','sashimi','Raw / Acid','Japanese art of slicing raw fish into precise pieces.','None','None','N/A','Maximum nutrition; sushi-grade fish required.','All nutrients intact; omega-3 fully preserved.','Tuna, salmon, yellowtail, octopus, scallop'),
('Crudo','crudo','Raw / Acid','Italian raw fish, thinly sliced with olive oil and citrus.','None','Olive oil + citrus','N/A','Heart-healthy olive oil fats; raw fish omega-3.','All nutrients intact.','Sea bass, tuna, scallops, shrimp'),
('Yukhoe','yukhoe','Raw / Acid','Korean raw beef with sesame oil, soy, egg yolk.','None','Sesame oil + soy + egg','N/A','High protein; raw egg adds fat-soluble vitamins.','All nutrients intact.','Beef tenderloin, Asian pear, egg yolk'),
('Kitfo','kitfo','Raw / Acid','Ethiopian raw minced beef with spiced butter (niter kibbeh) and mitmita spice.','None (or lightly warmed)','Spiced clarified butter','N/A','Rich in protein and iron; raw or leb leb (lightly cooked).','Maximum iron absorption; spiced butter adds vitamins.','Beef (kitfo), served with injera and ayib (cheese)'),
('Narezushi (Ancient Sushi)','narezushi','Raw / Acid','Japanese original sushi: fish fermented in rice for months. Predecessor to modern sushi.','None (fermentation)','Lactic acid from fermented rice','1–12 months','Deep fermentation; strong flavour. Rich in beneficial bacteria.','Enhanced B-vitamins; proteins partially broken down.','Carp, mackerel, sweetfish (funazushi)'),

-- MODERN
('Microwaving','microwaving','Modern','Cooking using microwave radiation exciting water molecules.','Variable (inside out)','Microwave radiation','1–10 min','Short time, no water = excellent nutrient retention.','Among best for vitamin C and B retention.','Reheating, steaming vegetables, defrosting'),
('Induction Cooking','induction-cooking','Modern','Electromagnetic heating of ferromagnetic cookware.','Variable (precise)','Electromagnetic induction','Variable','Same as conventional but more energy-efficient.','Depends on technique (sauté, boil, etc.).','Any stovetop cooking with compatible pans'),
('Combi Oven Cooking','combi-oven','Modern','Professional oven combining convection, steam, and microwave.','Variable (programmable)','Steam + convection + microwave','Variable','Precise control minimises overcooking.','Excellent — steam preserves water-soluble vitamins.','Professional: bread, roasts, vegetables, fish'),
('Smoking Gun','smoking-gun','Modern','Handheld cold-smoke device to infuse smoke without heat.','None (ambient)','Cold smoke from device','2–5 min','Minimal smoke exposure; flavour-focused.','Negligible impact.','Cocktails, butter, cheese, salmon, desserts'),
('Spherification','spherification','Modern','Sodium alginate + calcium gel spheres. Molecular gastronomy.','None (chemical)','Alginate + calcium bath','1–5 min','No heat involved.','Nutrients intact.','Olive oil pearls, juice caviar, cocktail garnishes'),
('Blowtorch / Brûlée','blowtorch','Modern','Direct flame from culinary torch for surface caramelisation.','Very High (surface only)','Butane / propane flame','10–60 sec','Surface-only heat; interior unchanged.','Negligible overall impact.','Crème brûlée, seared tuna, meringue, peppers'),
('Anti-Griddle (Freeze-Searing)','anti-griddle','Modern','Surface chilled to −34°C that flash-freezes food on contact. Molecular gastronomy.','Very Low (−34°C)','Frozen metal surface','10–60 sec','Freezes exterior while keeping interior liquid/soft.','Excellent — no heat applied.','Frozen purée discs, ice cream, chocolate ganache'),
('Centrifuge Cooking','centrifuge-cooking','Modern','Using a centrifuge to separate and clarify liquids for ultra-clear stocks and juices.','None (mechanical)','Centrifugal force','5–30 min','No heat; preserves heat-sensitive compounds.','Maximum — no thermal degradation.','Clarified tomato water, pea butter, consommé'),
('Rotary Evaporation','rotary-evaporation','Modern','Vacuum distillation to extract and concentrate volatile aromas at low temperature.','Low (vacuum reduces boiling point)','Vacuum + gentle heat','30 min–2 hrs','Preserves delicate volatile compounds that heat would destroy.','Excellent — captures aromatics without degradation.','Flavoured distillates, aromatic oils, cocktail essences');
