-- Seed Part 1: Dry Heat, Moist Heat, Fat-Based
-- Run AFTER: 20260224_alter_cooking_equipment_relationships.sql
-- NOTE: equipment_needed column was dropped; equipment_ids (uuid[]) populated separately via linking script
DELETE FROM catalog_cooking_methods;

INSERT INTO catalog_cooking_methods (name, slug, category, description, temperature, medium, typical_time, health_impact, nutrient_effect, best_for) VALUES
-- DRY HEAT
('Grilling','grilling','Dry Heat','Cooking over direct high heat on metal grates above a flame or coals.','High (230–370°C)','Direct flame / radiant heat','5–20 min','Can form HCAs/PAHs on charred surfaces; fat drips away.','Some B-vitamin loss; minerals well-retained.','Steaks, burgers, chicken, vegetables, seafood'),
('Broiling','broiling','Dry Heat','Cooking with intense direct heat from above, inside an oven.','High (260–290°C)','Radiant heat from above','5–15 min','Similar to grilling; fat drips away. Watch for charring.','Moderate vitamin loss from high heat.','Thin cuts of meat, fish fillets, vegetables'),
('Roasting','roasting','Dry Heat','Cooking uncovered in an oven with dry circulating heat.','Med-High (150–230°C)','Hot air (oven)','20 min–3 hrs','Retains nutrients well; Maillard reaction adds flavour.','Good mineral retention; some vitamin C loss.','Whole chicken, root vegetables, beef roasts'),
('Baking','baking','Dry Heat','Cooking in an enclosed oven using dry heat for doughs, batters, casseroles.','Medium (150–220°C)','Hot air (oven)','15 min–1 hr','Generally healthy; retention depends on ingredients and time.','B-vitamins can degrade in prolonged baking.','Bread, cakes, pastries, casseroles, gratins'),
('Sautéing','sauteing','Dry Heat','Quick cooking in small amount of fat over medium-high heat, tossing frequently.','Med-High (175–225°C)','Small amount of oil/fat','3–10 min','Minimal nutrient loss due to short cooking time.','Good vitamin and mineral retention.','Vegetables, shrimp, thin-cut meat, mushrooms'),
('Stir-Frying','stir-frying','Dry Heat','Very fast cooking in a wok over intense heat with minimal oil. Chinese origin.','Very High (200–300°C)','Wok + small amount of oil','2–8 min','Excellent nutrient retention due to very short cooking time.','Minimal vitamin loss; colours preserved.','Asian vegetables, noodles, thinly sliced meat, tofu'),
('Pan-Frying','pan-frying','Dry Heat','Cooking in moderate oil in a flat pan, food partially submerged.','Med-High (170–190°C)','Oil (partial immersion)','5–15 min','Higher fat absorption than sautéing; crispy exterior.','Some water-soluble vitamin loss.','Schnitzel, fish fillets, potato pancakes, eggs'),
('Deep-Frying','deep-frying','Dry Heat','Fully submerging food in hot oil for fast, even cooking.','High (175–190°C)','Oil (full immersion)','2–10 min','Significant fat absorption; acrylamide risk in starchy foods.','Water-soluble vitamins destroyed; minerals retained.','French fries, doughnuts, tempura, fried chicken'),
('Air Frying','air-frying','Dry Heat','Circulating superheated air to achieve crispy texture with minimal oil.','High (180–200°C)','Forced hot air + trace oil','8–25 min','Much less fat than deep-frying; lower acrylamide.','Better nutrient retention than deep-frying.','Fries, chicken wings, vegetables, fish'),
('Toasting','toasting','Dry Heat','Browning surface of bread, nuts, or seeds using dry radiant heat.','Med-High (150–230°C)','Radiant / contact heat','1–5 min','Minimal nutrient impact; acrylamide in over-toasted bread.','Negligible loss.','Bread, nuts, seeds, spices, coconut flakes'),
('Searing','searing','Dry Heat','Cooking surface at very high heat to form caramelised crust.','Very High (230–290°C)','Hot pan / grill','1–3 min/side','Maillard reaction for flavour; interior stays moist.','Minimal — mostly surface effect.','Steaks, tuna, duck breast, scallops'),
('Blackening','blackening','Dry Heat','Coating food in spices and cooking in very hot cast-iron until crust chars. Cajun origin.','Very High (260°C+)','Dry cast-iron pan','2–4 min/side','Spice char may contain trace carcinogens; portion small.','Spice antioxidants partially degraded.','Cajun fish, chicken, shrimp'),
('Rotisserie','rotisserie','Dry Heat','Slow-roasting on a rotating spit, self-basting as food turns.','Medium (150–200°C)','Radiant heat + rotation','1–4 hrs','Fat drips off; self-basting keeps meat moist.','Good retention overall.','Whole chicken, lamb leg, pork roast'),
('Tandoori','tandoori','Dry Heat','Cooking marinated food in cylindrical clay oven at extreme heat. Indian origin.','Very High (260–480°C)','Radiant clay-oven heat','8–20 min','Very fast cook; yoghurt marinades tenderise.','Quick cook preserves nutrients well.','Chicken tikka, naan, kebabs, paneer'),
('Dry Roasting','dry-roasting','Dry Heat','Roasting without any oil, relying on food''s own oils.','Medium (150–200°C)','Dry heat only','5–20 min','No added fat; brings out natural oils and flavours.','Minimal nutrient loss.','Spices, nuts, seeds, coffee beans, cacao'),
('Flash Frying','flash-frying','Dry Heat','Extremely brief deep-frying at very high temp to crisp exterior.','Very High (200°C+)','Oil (brief immersion)','10–30 sec','Minimal oil absorption due to brevity.','Excellent — interior barely heated.','Sashimi-grade tuna, soft-shell crab, herbs'),
('Plancha','plancha','Dry Heat','Cooking on a very hot flat metal plate. Spanish origin.','Very High (250–300°C)','Flat metal plate + trace oil','2–10 min','Quick sear; minimal fat needed on hot surface.','Good — short cooking time.','Seafood, vegetables, thin meats, peppers'),
('Salamander Grilling','salamander-grilling','Dry Heat','Professional overhead broiler for rapid browning and gratinating.','Very High (top heat)','Radiant heat from above','1–5 min','Brief surface browning; interior barely affected.','Negligible.','Gratins, crème brûlée, cheese melts, finishing dishes'),

-- MOIST HEAT
('Boiling','boiling','Moist Heat','Cooking fully submerged in water at 100°C with vigorous bubbles.','High (100°C)','Water','5–60 min','Significant leaching of water-soluble vitamins.','Up to 50% loss of vitamin C and B if water discarded.','Pasta, potatoes, eggs, grains, beans'),
('Simmering','simmering','Moist Heat','Gentle cooking just below boiling with small occasional bubbles.','Medium (85–96°C)','Water / stock','15 min–hrs','Gentler than boiling; nutrients leach into consumed liquid.','Better retention than boiling if broth eaten.','Soups, stews, sauces, rice, lentils'),
('Poaching','poaching','Moist Heat','Cooking gently in liquid held well below boiling point.','Low (70–85°C)','Water, stock, wine, milk','5–30 min','Very gentle; no added fat. Excellent for delicate proteins.','Some vitamin leaching; protein well-preserved.','Eggs, fish, chicken breast, fruit'),
('Blanching','blanching','Moist Heat','Brief immersion in boiling water followed by ice bath.','High then cold','Boiling water + ice water','30 sec–3 min','Preserves colour and texture; minimal nutrient loss.','Small vitamin C loss; enzymes deactivated.','Green vegetables, tomatoes (peeling), almonds'),
('Steaming','steaming','Moist Heat','Cooking over boiling water using steam; food never contacts liquid.','High (100°C steam)','Steam','5–25 min','One of healthiest methods; no fat, minimal leaching.','Best retention of water-soluble vitamins.','Vegetables, fish, dumplings, rice, tamales'),
('Double Boiling','double-boiling','Moist Heat','Heating in container over simmering water (bain-marie).','Low-Medium (up to 100°C)','Indirect steam/water bath','15 min–hrs','Very gentle; prevents scorching.','Moderate — nutrients transfer into liquid.','Chocolate, custards, herbal soups, sauces'),
('Pressure Cooking','pressure-cooking','Moist Heat','Cooking in sealed vessel where steam raises pressure and boiling point.','High (up to 121°C)','Pressurised steam','5–60 min','Faster cook = better nutrient retention; reduces anti-nutrients.','Retains more vitamins than conventional boiling.','Beans, tough meats, stocks, stews, grains'),
('Slow Cooking','slow-cooking','Moist Heat','Low-temperature cooking over many hours in covered vessel.','Low (80–95°C)','Liquid in sealed pot','4–12 hrs','Nutrients stay in liquid; collagen breaks into gelatin.','B-vitamins degrade over long time; minerals retained.','Stews, pulled pork, chili, bone broth, curries'),
('Sous Vide','sous-vide','Moist Heat','Vacuum-sealed food in precisely controlled water bath.','Low-Medium (50–85°C)','Controlled water bath','30 min–72 hrs','Exceptional nutrient and moisture retention.','Excellent — minimal leaching since sealed.','Steak, chicken breast, eggs, vegetables, fish'),
('Stewing','stewing','Moist Heat','Cooking small pieces submerged in liquid at gentle simmer.','Low-Medium (85–96°C)','Stock, wine, water','1–3 hrs','Nutrients transfer to consumed broth; collagen melts.','Good if broth consumed; some B-vitamin loss.','Beef stew, ratatouille, goulash, tagine'),
('Parboiling','parboiling','Moist Heat','Partially boiling food to soften before finishing differently.','High (100°C)','Water','3–10 min','Reduces total cooking time; some nutrient leaching.','Moderate vitamin C loss.','Potatoes (before roasting), rice, vegetables'),
('Scalding','scalding','Moist Heat','Heating liquid to just below boiling, or pouring hot liquid over food.','High (82°C)','Hot water or milk','1–5 min','Brief contact; loosens skins or kills surface bacteria.','Minimal — very brief exposure.','Milk (baking), tomatoes, peaches (peeling)'),
('Coddle','coddle','Moist Heat','Very gentle cooking in water just below simmering. Irish/British origin.','Low (70–80°C)','Warm water / covered vessel','30 min–2 hrs','Extremely gentle; preserves delicate texture.','Good retention; minimal agitation.','Eggs, Dublin coddle (sausages, bacon, potatoes)'),
('Reduction','reduction','Moist Heat','Simmering liquid uncovered to evaporate water and concentrate flavour.','Med-High (85–100°C)','Liquid evaporation','10 min–1 hr','Concentrates sodium, sugars, and flavour.','Minerals and fat-soluble vitamins concentrated.','Sauces, gravies, stocks, glazes, demi-glace'),
('Thermal / Haybox Cooking','thermal-cooker','Moist Heat','Bringing to boil then insulating in vacuum flask to finish with retained heat.','Starts high, then none','Retained heat (insulation)','2–8 hrs','Zero energy after initial boil; nutrients retained.','Good retention; sealed environment.','Soups, stews, porridge, grains, beans'),

-- FAT-BASED
('Confit','confit','Fat-Based','Slowly cooking food submerged in its own fat at low temperature. French origin.','Low (80–135°C)','Fat (duck fat, olive oil)','2–10 hrs','High fat absorption; slow cook preserves texture.','Protein retained; fat-soluble vitamins preserved.','Duck legs, garlic, tuna, pork belly'),
('Shallow Frying','shallow-frying','Fat-Based','Cooking in oil covering roughly half the food''s height.','Med-High (170–185°C)','Oil (half immersion)','5–12 min','Moderate fat absorption; less than deep-frying.','Some water-soluble vitamin loss.','Fish, cutlets, fritters, plantains'),
('Tempura Frying','tempura-frying','Fat-Based','Light cold batter, deep-fried briefly for airy shell. Japanese origin.','High (170–180°C)','Oil (full immersion)','2–4 min','Light batter absorbs less oil; very brief.','Quick fry preserves most nutrients.','Shrimp, vegetables, sweet potato, mushrooms'),
('Pakora / Bhaji Frying','pakora-frying','Fat-Based','Spiced chickpea batter deep-frying. South Asian origin.','High (175–185°C)','Oil (full immersion)','3–5 min','Chickpea batter adds protein; moderate oil absorption.','Moderate — quick fry preserves internal nutrients.','Onions, spinach, potatoes, cauliflower, paneer'),
('Karaage (Double-Fry)','karaage-frying','Fat-Based','Japanese double-fry: marinated pieces coated in starch, fried twice.','High (160 then 180°C)','Oil (double immersion)','6–8 min total','Double-fry = crispier shell, less oil retention.','Moderate; marinade adds flavour.','Chicken, octopus, tofu'),
('Beignet / Churro Frying','beignet-frying','Fat-Based','Frying enriched dough until puffed and golden. French/Spanish origin.','High (175–190°C)','Oil (full immersion)','2–4 min','High fat and sugar; treat food.','B-vitamins from flour partially retained.','Beignets, doughnuts, churros, zeppole'),
('Schmaltz Frying','schmaltz-frying','Fat-Based','Frying in rendered poultry fat. Ashkenazi Jewish origin.','Medium-High','Rendered chicken/goose fat','5–15 min','Rich flavour; high in monounsaturated fats.','Fat-soluble vitamin absorption enhanced.','Latkes, onions, matzo, potatoes, chopped liver'),
('Ghee Frying','ghee-frying','Fat-Based','Frying in clarified butter (ghee) which has higher smoke point. Indian origin.','High (250°C)','Clarified butter (ghee)','3–15 min','Higher smoke point than butter; rich in butyrate.','Fat-soluble nutrients well-absorbed.','Dosa, paratha, pakora, sweets');
