-- Seed Part 3: Specialty / Regional methods from ALL world cultures
-- Run AFTER Part 2
-- NOTE: equipment_needed column was dropped; equipment_ids (uuid[]) populated separately via linking script

INSERT INTO catalog_cooking_methods (name, slug, category, description, temperature, medium, typical_time, health_impact, nutrient_effect, best_for) VALUES

-- AFRICA
('Potjiekos','potjiekos','Specialty','South African layered stew in round cast-iron pot over coals. Afrikaans origin.','Low-Medium (coals)','Cast-iron pot over coals','2–4 hrs','Slow gentle cooking; nutrients stay in pot.','Good — consumed with all cooking liquid.'),
('Thieboudienne','thieboudienne','Specialty','Senegalese one-pot rice and fish simmered in tomato sauce.','Medium','Tomato stock + oil','1–2 hrs','Balanced one-pot meal; tomato provides lycopene.','Good; nutrients retained in sauce.'),
('Suya Grilling','suya-grilling','Specialty','West African spiced meat grilled on skewers over charcoal. Hausa/Nigerian origin.','High (charcoal)','Charcoal + spice crust','10–20 min','Peanut rub adds protein; some charring risk.','Quick grill preserves nutrients.'),
('Dibi Grilling','dibi-grilling','Specialty','Senegalese/Malian grilled lamb charred over coals, served chopped.','High (charcoal)','Charcoal fire','20–40 min','Fat renders off; high-heat char.','Good protein retention.','Lamb, goat'),
('Braaivleis (Braai)','braai','Specialty','South African barbecue over wood/charcoal. Cultural tradition.','High (wood fire)','Wood/charcoal fire','30 min–3 hrs','Fat drips away; wood smoke adds flavour.','Good mineral retention.','Boerewors, steak, lamb chops, sosaties, mielies'),
('Tagine Cooking','tagine-cooking','Specialty','Moroccan/North African slow cooking in conical clay pot that returns condensation.','Low-Medium','Clay tagine + stove/coals','1–3 hrs','Conical lid recirculates steam; no moisture lost.','Excellent — sealed moist environment.','Lamb tagine, chicken, vegetables, couscous'),
('Couscous Steaming','couscous-steaming','Specialty','North African method of steaming couscous over a bubbling stew in a couscoussier.','High (steam)','Steam from stew below','30–60 min','Steamed grain absorbs stew flavours; no added fat.','Good; steam preserves grain nutrients.','Couscous with lamb, chicken, or vegetable stew'),
('Mshikaki Grilling','mshikaki','Specialty','East African (Swahili) marinated meat skewers grilled over charcoal.','High (charcoal)','Charcoal fire','10–15 min','Quick grill; marinade adds flavour.','Good — short cooking time.','Beef, goat, chicken'),
('Nyama Choma','nyama-choma','Specialty','East African (Kenyan) slow-grilled meat over charcoal. National dish of Kenya.','Medium-High (charcoal)','Charcoal fire','30–60 min','Fat renders off; traditional social food.','Good mineral retention.','Goat, beef, chicken'),

-- MIDDLE EAST
('Saj Bread Baking','saj-baking','Specialty','Baking flatbread on a domed metal griddle (saj) over open flame. Levantine origin.','Very High','Domed metal plate + fire','1–3 min','Ultra-thin bread; very fast bake.','Minimal loss — very brief.','Saj bread, markook, lavash'),
('Tannour / Taboun Baking','tannour-baking','Specialty','Baking bread in a clay barrel oven or buried clay pot. Ancient Mesopotamian origin.','Very High (clay oven)','Radiant clay heat','2–5 min','Quick bake in intense heat; bread slightly charred.','Quick cook preserves most nutrients.','Tannour bread, taboon bread, samoon'),
('Mansaf Cooking','mansaf-cooking','Specialty','Jordanian ceremonial dish: lamb slow-cooked in dried yoghurt sauce (jameed).','Medium (simmering)','Reconstituted jameed + stock','2–3 hrs','Yoghurt provides probiotics and calcium; lamb adds iron.','Minerals retained in consumed sauce.','Mansaf (lamb, rice, jameed sauce)'),
('Meshwi (Charcoal Grilling)','meshwi','Specialty','Lebanese/Arab charcoal grilling of marinated meats on skewers.','High (charcoal)','Charcoal fire','10–20 min','Quick grill; marinades add antioxidants.','Good — short cooking time.','Lamb kebabs, chicken tawook, kafta'),
('Makloubeh (Flipped Pot)','makloubeh','Specialty','Palestinian layered rice, meat, and vegetables cooked in pot then flipped upside down.','Medium','Stock + oil','1–2 hrs','One-pot balanced meal.','Good — nutrients retained in pot.','Makloubeh (chicken/lamb, eggplant, rice)'),

-- SOUTH ASIA
('Dum Pukht (Dum Cooking)','dum-pukht','Specialty','Mughlai slow-cooking: sealing pot with dough on very low heat. Indian origin.','Low (gentle dum)','Sealed pot + low fire','1–3 hrs','Sealed preserves all moisture and aromatics.','Excellent — no steam escapes.','Biryani, nihari, kebabs, dum aloo'),
('Bhunao (Bhuna)','bhunao','Specialty','Indian high-heat frying of paste and spices until oil separates.','High','Oil + spice paste','10–30 min','Oil separation = spices fully cooked; concentrated flavour.','Spice antioxidants; oil aids fat-soluble absorption.','Bhuna gosht, bhuna chicken, base gravies'),
('Tadka / Tarka / Baghar','tadka','Specialty','Tempering whole spices in hot oil/ghee, poured over dish. Indian subcontinent.','High (brief)','Hot ghee or oil','30 sec–2 min','Releases fat-soluble spice compounds. Aromatic.','Enhances bioavailability of curcumin etc.','Dal, raita, chutneys, rice dishes'),
('Handi Cooking','handi-cooking','Specialty','Narrow-necked wide-bellied clay/metal pot cooking. Mughlai origin.','Low-Medium','Handi pot + sealed lid','1–3 hrs','Shape traps steam; self-basting. Rich results.','Good — sealed slow cooking.','Handi biryani, korma, gosht, dal'),
('Sigdi / Angeethi','sigdi-cooking','Specialty','Pakistani/Indian street cooking on portable charcoal stove.','Variable (charcoal)','Charcoal heat','Variable','Direct charcoal; smoky flavour.','Depends on technique.','Chapati, kebabs, chai, dal'),
('Undhiyu (Matla Cooking)','undhiyu','Specialty','Gujarati method of cooking vegetables upside-down in earthen pot buried in coals.','Low-Medium (coals)','Earthen pot + coals','2–3 hrs','Slow underground cook; no added water. Earthy flavour.','Excellent — sealed, self-steaming.','Undhiyu (mixed winter vegetables, fenugreek dumplings)'),
('Patrani (Leaf-Wrapped Steaming)','patrani','Specialty','Parsi Indian method of wrapping fish in banana leaf with chutney and steaming.','Medium (steam)','Banana leaf + steam','15–20 min','No added fat; leaf seals moisture.','Excellent retention.','Patrani macchi (fish), chutney'),

-- EAST ASIA
('Wok Hei','wok-hei','Specialty','Breath of the wok — extreme-heat wok cooking for smoky aroma. Chinese origin.','Extreme (300°C+)','Wok over jet burner','1–3 min','Ultra-fast; minimal nutrient loss.','Excellent due to extreme speed.','Stir-fry, fried rice, noodles'),
('Clay Pot (Sha Guo)','sha-guo','Specialty','Chinese clay pot for rice, stews, soups. Retains and distributes heat evenly.','Medium (150–200°C)','Clay vessel + stove','30 min–3 hrs','Excellent moisture retention; porous clay self-bastes.','Nutrients retained in sealed pot.','Claypot rice, soups, braised dishes'),
('Teppanyaki','teppanyaki','Specialty','Japanese cooking on large flat iron griddle at tableside.','Very High (230–260°C)','Flat iron griddle + oil','5–15 min','Quick cook on hot surface; minimal oil.','Good; quick cook preserves nutrients.','Steak, shrimp, scallops, vegetables, fried rice'),
('Robatayaki','robatayaki','Specialty','Japanese fireside grilling on skewers over charcoal.','High (charcoal)','Binchotan charcoal','5–15 min','Gentle charcoal; wide range of ingredients.','Good retention; quick cooking.','Fish, shellfish, vegetables, tofu, mochi'),
('Kamado Cooking','kamado-cooking','Specialty','Thick-walled ceramic egg-shaped oven. Japanese origin (Big Green Egg).','Variable (80–370°C)','Charcoal + ceramic insulation','Variable','Excellent heat retention and moisture.','Depends on technique.','Pizza, brisket, chicken, bread, vegetables'),
('Mongolian Hot Pot','mongolian-hot-pot','Specialty','Communal cooking in simmering broth at table, dipping thin-sliced ingredients.','High (simmering)','Simmering broth','10 sec–5 min','Brief cooking preserves nutrients; social eating.','Excellent for quick-cooked items.','Thin-sliced lamb/beef, tofu, mushrooms, greens'),
('Shabu-Shabu','shabu-shabu','Specialty','Japanese hot pot variant — swishing thin meat in kombu broth briefly.','High (simmering)','Kombu dashi broth','5–15 sec/slice','Very brief; maximum nutrient retention.','Excellent — barely cooked.','Wagyu/beef, pork, vegetables, udon'),
('Chahan (Wok Fried Rice)','chahan','Specialty','Japanese/Chinese high-heat wok-tossed fried rice technique.','Very High','Wok + oil','3–5 min','Quick; egg and vegetables add nutrition.','Good — very brief heating.','Fried rice with egg, vegetables, meat'),
('Red Cooking (Hong Shao)','hong-shao','Specialty','Chinese technique of braising in soy sauce, sugar, and spices until deep red-brown.','Low-Medium','Soy sauce + sugar + stock','1–3 hrs','Rich in umami; soy adds protein. Sugar adds calories.','Minerals well-retained in sauce.','Pork belly, tofu, fish, eggs'),
('Lap Cheong Steaming','lap-cheong-steaming','Specialty','Cantonese method of steaming rice with Chinese sausage on top so fat melts into rice.','High (steam)','Steam','20–30 min','Sausage fat flavours rice; no extra oil needed.','Good grain and protein combo.','Lap cheong (Chinese sausage), rice'),
('Peking Duck Roasting','peking-duck','Specialty','Chinese technique: air-dried duck glazed with maltose, roasted in hung oven for crispy skin.','High (260°C)','Hung oven / closed oven','45–60 min','Skin rendered crispy; fat mostly rendered off.','Protein well-retained; crispy skin is mostly rendered.','Peking duck'),
('Dak-galbi (Iron Plate)','dak-galbi','Specialty','Korean spicy chicken stir-fried on large iron plate at tableside.','High','Large flat iron plate','10–15 min','Quick cook; gochujang adds capsaicin (metabolism boost).','Good — short cook time.','Spicy chicken, rice cakes, cabbage, sweet potato'),

-- SOUTHEAST ASIA
('Banana Leaf Steaming','banana-leaf-steaming','Specialty','Wrapping food in banana leaves and steaming or grilling. Pan-Asian/Pacific.','Medium','Banana leaf + steam/fire','20–60 min','Leaf seals moisture; no fat needed. Subtle flavour.','Excellent — sealed moist cooking.','Fish, rice (lontong), tamales, kakanin'),
('Bamboo Tube Cooking','khao-lam','Specialty','Food stuffed into bamboo tubes and roasted over fire. Thai/Lao origin.','Medium (fire)','Bamboo tube + fire','1–2 hrs','Bamboo adds subtle sweet flavour; sealed steaming.','Good retention; sealed tube.','Sticky rice (khao lam), meat, fish'),
('Rendang (Slow Dry Curry)','rendang','Specialty','Indonesian/Malay meat slow-cooked in coconut and spices until dry. Minangkabau origin.','Medium then low','Coconut milk + spices','3–6 hrs','Coconut provides MCTs; spices add antioxidants. Long cook concentrates.','Minerals concentrated; some vitamin loss from duration.','Beef rendang, chicken rendang, jackfruit'),
('Satay Grilling','satay-grilling','Specialty','Skewered marinated meat grilled over charcoal with peanut sauce. Indonesian origin.','High (charcoal)','Charcoal fire','5–10 min','Quick grill; peanut sauce adds protein.','Good — short cooking time.','Chicken, beef, pork, lamb satay'),
('Soto (Long-Simmered Broth)','soto-cooking','Specialty','Indonesian aromatic broth simmered for hours with turmeric and galangal.','Low-Medium','Spiced stock','2–4 hrs','Turmeric adds curcumin; bone broth adds collagen.','Minerals leach into consumed broth; turmeric antioxidants.','Soto ayam, soto betawi, soto madura'),
('Otak-Otak (Leaf Grilling)','otak-otak','Specialty','Malaysian/Singaporean fish paste grilled in banana leaf parcels.','Medium (grill)','Banana leaf + grill','10–15 min','Fish paste is protein-rich; coconut adds MCTs.','Good; leaf preserves moisture.','Otak-otak (spiced fish paste)'),

-- KOREA
('Dolsot (Stone Pot)','dolsot','Specialty','Searing-hot stone bowl creates crispy rice crust (nurungji). Korean origin.','Very High (stone)','Preheated stone bowl','5–10 min','Crispy rice without added oil; stone retains heat.','Minimal; mainly finishing technique.','Bibimbap, rice dishes'),
('Bulgogi Grilling','bulgogi','Specialty','Thin-sliced marinated beef on domed griddle. Korean origin.','High','Charcoal or griddle','2–5 min','Very quick; marinade tenderises.','Good; short cooking time.','Beef bulgogi, daeji bulgogi, chicken'),
('Ssam (Leaf Wrapping)','ssam','Specialty','Wrapping grilled or braised meat in fresh leaves with condiments.','None (assembly)','Raw leaf wraps','N/A','Raw leaves add fibre and vitamins.','Excellent — raw vegetables.','Grilled pork belly, bossam, lettuce, perilla'),
('Jjim (Korean Steaming/Braising)','jjim','Specialty','Korean braised or steamed dishes cooked slowly until tender.','Low-Medium','Soy-based braising liquid','1–3 hrs','Gentle cook; soy adds umami and protein.','Good; sauce consumed.','Galbi-jjim (short ribs), gyeran-jjim (egg)'),
('Jeongol (Table Hot Pot)','jeongol','Specialty','Korean table-cooked stew in wide shallow pot over burner.','Medium-High','Broth at table','15–30 min','Fresh ingredients added progressively.','Good — brief cooking.','Budae-jjigae, mandu jeongol, haemul jeongol'),
('Gochujang Glazing','gochujang-glazing','Specialty','Coating food in fermented chili paste and grilling or roasting.','Medium-High','Gochujang + heat','10–20 min','Capsaicin boosts metabolism; fermented paste has probiotics.','Antioxidants from chili; some loss from heat.','Chicken wings, pork, tofu, vegetables'),

-- JAPAN (additional)
('Nabemono (One-Pot)','nabemono','Specialty','Japanese family-style one-pot simmered at table. Winter tradition.','Medium (simmering)','Dashi or stock at table','20–40 min','Balanced meal; vegetables and protein cooked gently.','Good — broth consumed.','Chanko nabe, oden, sukiyaki, yosenabe'),
('Kushiage / Kushikatsu','kushiage','Specialty','Osaka-style skewered and breadcrumbed deep-fried bites.','High (175–180°C)','Oil (full immersion)','1–3 min/piece','Light panko coating; very brief fry.','Moderate; quick fry.','Meat, seafood, vegetables on skewers'),
('Nimono (Simmered Dishes)','nimono','Specialty','Japanese simmering in dashi, soy, mirin, and sake.','Low-Medium','Dashi-based liquid','20–60 min','Gentle simmer; dashi provides umami without fat.','Good; consumed with braising liquid.','Kabocha, daikon, fish, tofu, root vegetables'),
('Mushimono (Steamed)','mushimono','Specialty','Japanese steaming technique for delicate custards and fish.','High (steam)','Steam','15–30 min','No fat; very gentle. One of healthiest Japanese methods.','Excellent retention.','Chawanmushi (egg custard), steamed fish'),
('Takikomi Gohan','takikomi-gohan','Specialty','Japanese seasoned rice cooked with vegetables and protein in one pot.','Medium','Dashi + soy in rice cooker','30–45 min','One-pot balanced meal; dashi adds umami.','Good; nutrients in consumed liquid.','Seasoned rice with mushrooms, chicken, burdock'),
('Tataki','tataki','Specialty','Japanese technique of briefly searing outside of fish/meat while keeping inside raw.','Very High (brief sear)','Hot pan + ice bath','30 sec–1 min/side','Mostly raw; maximum nutrition with Maillard crust.','Excellent — interior raw.','Tuna tataki, bonito tataki, beef tataki'),

-- AMERICAS
('Pit Cooking / Barbacoa','barbacoa','Specialty','Mexican/Caribbean underground pit cooking wrapped in maguey leaves.','Medium (retained heat)','Hot coals + leaves + earth','6–12 hrs','Slow underground roast; extremely tender.','Good — sealed environment.','Barbacoa (beef cheeks, lamb), cochinita pibil'),
('Cochinita Pibil','pib-cooking','Specialty','Yucatecan Mayan underground pit cooking with achiote and banana leaf.','Medium (retained heat)','Hot coals + banana leaves','6–12 hrs','Achiote adds antioxidants; sealed slow-roast.','Good retention; sealed with leaves.','Cochinita pibil (pork), mukbil pollo'),
('Nixtamalization','nixtamalization','Specialty','Mesoamerican process of soaking corn in alkaline solution (cal/lime) to release niacin.','Medium (simmering)','Alkaline water (cal)','30 min + soak','Releases bound niacin (B3); prevents pellagra. Revolutionary process.','Dramatically increases niacin bioavailability; calcium added.','Masa for tortillas, tamales, hominy, pozole'),
('Planking (Indigenous)','indigenous-planking','Specialty','First Nations cedar-plank cooking of salmon beside open fire.','Medium (indirect)','Cedar plank + fire','30–60 min','Wood infuses flavour; indirect heat is gentle.','Good — slow, moist cooking.','Salmon, trout'),
('Clambake','clambake','Specialty','New England pit/beach cooking: layered seaweed, shellfish, corn over hot rocks.','Medium (steam from seaweed)','Hot rocks + seaweed steam','1–2 hrs','Seaweed adds minerals (iodine); steaming preserves nutrients.','Excellent — steam cooking.','Clams, lobster, corn, potatoes, mussels'),
('Smoke Roasting (American BBQ)','american-bbq','Specialty','Low-and-slow smoking of large cuts over indirect wood smoke. American South origin.','Low (95–135°C)','Wood smoke + indirect heat','4–18 hrs','Long smoke exposure; collagen melts. PAH concern with heavy smoke.','Protein well-retained; some B-vitamin loss.','Brisket, pulled pork, ribs, sausage'),
('Chimichurri Grilling','chimichurri-grilling','Specialty','Argentine method of grilling with chimichurri herb sauce basting.','High','Charcoal + chimichurri','10–30 min','Herb sauce adds antioxidants; parsley rich in vitamin C.','Quick grill preserves nutrients; herbs add vitamins.','Steak, short ribs, chicken'),
('Curanto','curanto','Specialty','Chilean/Patagonian underground cooking with hot stones, shellfish, meat, potatoes. Mapuche/Chiloé origin.','Medium (retained heat)','Hot stones + leaves + earth','2–4 hrs','Diverse ingredients; sealed earth oven.','Good — sealed environment.','Shellfish, pork, chicken, potatoes, milcao'),

-- EUROPE
('Salt Baking','salt-baking','Specialty','Encasing food in thick salt crust and baking. Mediterranean origin.','Medium (200–230°C)','Salt crust + oven','25–50 min','Food doesn''t absorb much salt; steams inside.','Excellent — sealed, moist.','Whole fish, chicken, beets, potatoes'),
('Plancha (Spanish)','plancha-spanish','Specialty','Very hot flat metal plate cooking. Spanish origin.','Very High (250–300°C)','Flat metal plate','2–10 min','Quick sear; minimal fat.','Good — short cooking time.','Seafood, vegetables, meats'),
('Pierogi Boiling + Frying','pierogi-cooking','Specialty','Polish method: boil dumplings first, then pan-fry in butter. Two-stage.','High then Medium','Water then butter','10–15 min','Boiling cooks through; butter adds flavour and calories.','Moderate; some leaching then fat absorption.','Pierogi (various fillings)'),
('Gratinating','gratinating','Specialty','Finishing a dish under high heat to brown cheese/breadcrumb topping. French origin.','Very High (top heat)','Radiant heat from above','3–10 min','Brief surface browning.','Negligible overall impact.','Gratin dauphinois, croque monsieur, mac and cheese'),
('Smoking with Juniper','juniper-smoking','Specialty','Scandinavian smoking with juniper branches for aromatic preservation.','Low-Medium','Juniper smoke','2–12 hrs','Juniper adds antibacterial properties and flavour.','Protein retained; juniper antioxidants.','Lamb, reindeer, salmon, cheese'),
('Spit-Roasting (Souvla)','souvla','Specialty','Cypriot/Greek whole-animal spit roasting over charcoal.','Medium (rotation)','Charcoal + spit','2–5 hrs','Fat renders away; self-basting.','Good overall retention.','Lamb, pork, chicken (souvla/souvlaki)'),
('Stufato / Italian Stewing','stufato','Specialty','Italian slow-braised stew with wine, tomatoes, and aromatics.','Low-Medium','Wine + tomato + stock','2–4 hrs','Wine antioxidants; tomato lycopene. Slow cook tenderises.','Minerals retained in sauce.','Beef stufato, ossobuco, peposo'),
('Pierrade (Hot Stone Table)','pierrade','Specialty','French/Swiss table cooking on heated stone slab.','Very High (stone surface)','Preheated stone','1–3 min/piece','No added fat; meat cooks on own juices.','Good — brief, direct heat.','Thin meats, seafood, vegetables'),
('Smørrebrød Assembly','smorrebrod','Specialty','Danish open sandwich assembly technique — layered cold preparations.','None (assembly)','None','N/A','Raw and cured ingredients; nutrient-dense.','Maximum — no heat applied.','Rye bread, herring, liver pâté, shrimp, egg'),
('Canning / Bottling (Einkochen)','einkochen','Specialty','German/European method of preserving food in sealed glass jars with heat processing.','High (100°C water bath or 116°C pressure)','Boiling water bath or pressure','30 min–2 hrs','Long-term preservation; some heat-sensitive vitamin loss.','Moderate vitamin C loss; minerals retained.','Jams, pickles, sauces, fruits, vegetables'),

-- OCEANIA / PACIFIC
('Imu (Hawaiian Earth Oven)','imu','Specialty','Hawaiian underground oven with hot lava rocks and ti/banana leaves.','Medium (retained heat)','Hot lava rocks + leaves','8–16 hrs','Slow sealed cook; extremely tender.','Excellent — sealed.','Kalua pig, taro, sweet potato, fish'),
('Hāngi','hangi','Specialty','Māori earth oven with hot stones. New Zealand cultural ceremony.','Medium (retained heat)','Hot stones + earth','3–6 hrs','Underground steam-roast; very moist.','Good — sealed environment.','Pork, chicken, kumara, pumpkin, cabbage'),
('Lovo','lovo','Specialty','Fijian earth oven similar to hāngi, using coconut husks and hot stones.','Medium (retained heat)','Hot stones + coconut husks + leaves','3–5 hrs','Coconut husk smoke adds flavour; slow cook tenderises.','Good — sealed.','Pork, fish, taro, cassava, palusami'),
('Umu','umu','Specialty','Samoan/Tongan above-ground stone oven using heated volcanic rocks.','High (hot stones)','Volcanic stones + leaves','1–3 hrs','Above-ground variant; hot stones provide intense heat.','Good; sealed with leaves.','Pig, breadfruit, taro, lu (taro leaf parcels)'),

-- MISCELLANEOUS / CROSS-CULTURAL
('Smoking and Curing (Charcuterie)','charcuterie','Specialty','Art of curing, smoking, and ageing meats. French/Italian/Spanish/German traditions.','Variable','Salt, smoke, air, time','Days–months','Concentrated protein; high sodium. Nitrate debate.','Minerals concentrated; enzymes develop flavour.','Prosciutto, bresaola, soppressata, jamón, nduja'),
('Cheese Making (Affinage)','affinage','Specialty','Ageing cheese in controlled conditions to develop flavour and texture.','Cool ambient (10–15°C)','Bacterial/mould cultures + time','Weeks–years','Calcium and protein concentrated; probiotics in some.','Enhanced calcium; B12 from bacterial action.','Aged cheddar, Parmesan, Gruyère, blue cheese'),
('Smoking with Tea (Tea-Smoking)','tea-smoking','Specialty','Chinese method of smoking food over smouldering tea leaves, rice, and sugar.','Low-Medium','Tea leaf + rice + sugar smoke','15–30 min','Light smoke; tea polyphenols add antioxidants.','Moderate; tea antioxidants partially transferred.','Duck, chicken, salmon, tofu, eggs'),
('Butter Poaching','butter-poaching','Specialty','Gently cooking food submerged in melted butter at low temperature.','Low (70–80°C)','Melted butter','10–30 min','Rich; butter adds calories but excellent flavour.','Fat-soluble vitamin absorption enhanced.','Lobster, fish, asparagus, root vegetables'),
('Oil Poaching','oil-poaching','Specialty','Gently cooking food submerged in olive or other oil at low temperature.','Low (60–80°C)','Olive oil or neutral oil','15–45 min','Gentle; olive oil adds heart-healthy fats.','Fat-soluble vitamin absorption enhanced.','Fish, garlic, tomatoes, peppers'),
('Hay-Box / Retained Heat','haybox','Specialty','Ancient energy-saving method: bring to boil, insulate to finish cooking.','Starts high, then none','Retained heat (insulation)','2–8 hrs','Zero energy after boil; nutrients retained.','Good; sealed environment.','Soups, stews, porridge, beans'),
('Ash Cooking','ash-cooking','Specialty','Burying food directly in hot wood ash for slow roasting. Ancient worldwide.','Medium-High (ash heat)','Hot wood ash','20–60 min','Gentle indirect heat; ash provides minerals (potassium).','Minerals from ash can transfer to food.','Potatoes, corn, onions, flatbread, eggs'),
('Plank/Board Curing (Gravadlax)','gravadlax','Specialty','Scandinavian method of curing salmon with salt, sugar, and dill between boards.','None (ambient/cold)','Salt + sugar + dill','2–5 days','No heat; salt draws moisture. High omega-3 retained.','Excellent — raw, cured fish.','Gravadlax (cured salmon)'),
('Chocolate Tempering','chocolate-tempering','Specialty','Precisely heating and cooling chocolate to form stable cocoa butter crystals.','Low (27–32°C)','Indirect heat (bain-marie)','20–40 min','Temperature precision; preserves antioxidants in cacao.','Antioxidant retention excellent at low temps.','Chocolate bars, truffles, bonbons, coating'),
('Sprouting','sprouting','Specialty','Germinating seeds/beans to increase nutrition before eating raw or cooking.','None (ambient, moist)','Water + air','2–7 days','Increases vitamins (C, folate), reduces anti-nutrients.','Dramatically increases vitamin C and folate content.','Bean sprouts, alfalfa, broccoli sprouts, lentils'),
('Nixtamalization (Ash/Lime)','nixtamalization-ash','Specialty','African/Native American method of treating grain with wood ash or lime to increase nutrition.','Medium','Alkaline solution (ash/lime)','30 min + soak','Releases niacin; adds calcium. Prevents pellagra.','Niacin bioavailability dramatically increased.','Corn/maize for tortillas, ugali, porridge','Pot, wood ash or cal (calcium hydroxide), corn, water');
